# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.create_filter_object_ds_api import CreateFilterObjectDSApi

class TestCreateFilterObjectDSApi(unittest.TestCase):
    """CreateFilterObjectDSApi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFilterObjectDSApi:
        """Test CreateFilterObjectDSApi
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFilterObjectDSApi`
        """
        model = CreateFilterObjectDSApi()
        if include_optional:
            return CreateFilterObjectDSApi(
                filter_general = None,
                filter_add_services = feratel_client.models.filter_add_services.FilterAddServices(
                    types = [
                        ''
                        ], 
                    holiday_themes = [
                        ''
                        ], 
                    locations = [
                        ''
                        ], 
                    guest_cards = [
                        feratel_client.models.guest_card_filter.GuestCardFilter(
                            id = '', 
                            type = 56, )
                        ], 
                    name = '', 
                    service_classifications = [
                        ''
                        ], 
                    top_service_classifications = [
                        ''
                        ], 
                    top_service_classifications_behaviour = 0, ),
                filter_accommodation = feratel_client.models.filter_accommodation.FilterAccommodation(
                    categories = [
                        ''
                        ], 
                    locations = [
                        ''
                        ], 
                    rooms = [
                        56
                        ], 
                    bedrooms = [
                        56
                        ], 
                    stars = [
                        ''
                        ], 
                    criterias = [
                        ''
                        ], 
                    criterias_behaviour = 0, 
                    classifications = [
                        ''
                        ], 
                    top_classifications = [
                        ''
                        ], 
                    top_classifications_behaviour = 0, 
                    marketinggroups = [
                        ''
                        ], 
                    name = '', 
                    price = feratel_client.models.price_filter.PriceFilter(
                        from = 1.337, 
                        to = 1.337, ), 
                    best_price = True, 
                    special_price = True, 
                    special_offer = True, 
                    package_categories = [
                        ''
                        ], ),
                filter_event = feratel_client.models.filter_event.FilterEvent(
                    top_event = True, 
                    locations = [
                        ''
                        ], 
                    criteria_groups = [
                        ''
                        ], 
                    criteria = [
                        ''
                        ], 
                    event_groups = [
                        ''
                        ], 
                    holiday_themes = [
                        ''
                        ], 
                    name = '', 
                    guest_cards = [
                        feratel_client.models.guest_card_filter.GuestCardFilter(
                            id = '', 
                            type = 56, )
                        ], 
                    classifications = [
                        ''
                        ], 
                    top_classifications = [
                        ''
                        ], 
                    top_classifications_behaviour = 0, ),
                filter_infrastructure = feratel_client.models.filter_infrastructure.FilterInfrastructure(
                    opening_times = [
                        56
                        ], 
                    infrastructure_types = [
                        ''
                        ], 
                    locations = [
                        ''
                        ], 
                    holiday_themes = [
                        ''
                        ], 
                    name = '', 
                    topics = [
                        ''
                        ], 
                    topics_behaviour = 0, 
                    guest_cards = [
                        feratel_client.models.guest_card_filter.GuestCardFilter(
                            id = '', 
                            type = 56, )
                        ], 
                    classifications = [
                        ''
                        ], 
                    top_classifications = [
                        ''
                        ], 
                    top_classifications_behaviour = 0, ),
                filter_brochure = feratel_client.models.filter_brochure.FilterBrochure(
                    languages = [
                        ''
                        ], 
                    holiday_themes = [
                        ''
                        ], 
                    brochure_groups = [
                        ''
                        ], 
                    name = '', ),
                filter_package = feratel_client.models.filter_package.FilterPackage(
                    groups = [
                        ''
                        ], 
                    holiday_themes = [
                        ''
                        ], 
                    name = '', ),
                filter_tour = feratel_client.models.filter_tour.FilterTour(
                    languages = [
                        ''
                        ], 
                    categories = [
                        ''
                        ], 
                    holiday_themes = [
                        ''
                        ], 
                    name = '', 
                    top_tour = True, 
                    classifications = [
                        ''
                        ], 
                    top_classifications = [
                        ''
                        ], 
                    top_classifications_behaviour = 0, )
            )
        else:
            return CreateFilterObjectDSApi(
        )
        """

    def testCreateFilterObjectDSApi(self):
        """Test CreateFilterObjectDSApi"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
