# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.rating_type import RatingType

class TestRatingType(unittest.TestCase):
    """RatingType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRatingType(self):
        """Test RatingType"""
        # inst = RatingType()

if __name__ == '__main__':
    unittest.main()
