# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.add_item_linked_data_gateway_command import AddItemLinkedDataGatewayCommand

class TestAddItemLinkedDataGatewayCommand(unittest.TestCase):
    """AddItemLinkedDataGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddItemLinkedDataGatewayCommand:
        """Test AddItemLinkedDataGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddItemLinkedDataGatewayCommand`
        """
        model = AddItemLinkedDataGatewayCommand()
        if include_optional:
            return AddItemLinkedDataGatewayCommand(
                link_type = 0,
                parent_type = 0,
                parent_id = ''
            )
        else:
            return AddItemLinkedDataGatewayCommand(
        )
        """

    def testAddItemLinkedDataGatewayCommand(self):
        """Test AddItemLinkedDataGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
