# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.salutation_sex import SalutationSex

class TestSalutationSex(unittest.TestCase):
    """SalutationSex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSalutationSex(self):
        """Test SalutationSex"""
        # inst = SalutationSex()

if __name__ == '__main__':
    unittest.main()
