# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.ski_data_package_item import SkiDataPackageItem

class TestSkiDataPackageItem(unittest.TestCase):
    """SkiDataPackageItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SkiDataPackageItem:
        """Test SkiDataPackageItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SkiDataPackageItem`
        """
        model = SkiDataPackageItem()
        if include_optional:
            return SkiDataPackageItem(
                id = '',
                item_id = '',
                service_id = '',
                type = 0,
                deposit_fee_product_id = '',
                person = feratel_client.models.external_person_information_data.ExternalPersonInformationData(
                    guest_portal_user_id = '', 
                    title = 100, 
                    first_name = '', 
                    last_name = '', 
                    date_of_birth = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    picture = '', ),
                ski_data_input_data = feratel_client.models.ski_data_package_item_ticket_input_data.SkiDataPackageItemTicketInputData(
                    chip_id = '', 
                    serial_number = '', 
                    luhn = '', 
                    picture = '', ),
                swiss_pass_data = feratel_client.models.swiss_pass_data.SwissPassData(
                    swiss_pass_id = '', 
                    zip_code = '', ),
                age_restriction = feratel_client.models.additional_service_age_restriction.AdditionalServiceAgeRestriction(
                    has_age_restriction = True, 
                    use_age = True, 
                    from = 56, 
                    to = 56, 
                    values = [
                        56
                        ], ),
                white_list = [
                    ''
                    ],
                black_list = [
                    ''
                    ]
            )
        else:
            return SkiDataPackageItem(
        )
        """

    def testSkiDataPackageItem(self):
        """Test SkiDataPackageItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
