# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.api.add_services_api import AddServicesApi


class TestAddServicesApi(unittest.IsolatedAsyncioTestCase):
    """AddServicesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AddServicesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_addservices_linkkey_lang_filterresults_filter_id_get(self) -> None:
        """Test case for addservices_linkkey_lang_filterresults_filter_id_get

        """
        pass

    async def test_addservices_linkkey_lang_filterresults_get(self) -> None:
        """Test case for addservices_linkkey_lang_filterresults_get

        """
        pass

    async def test_addservices_linkkey_lang_searchresults_search_id_filterresults_filter_id_get(self) -> None:
        """Test case for addservices_linkkey_lang_searchresults_search_id_filterresults_filter_id_get

        """
        pass

    async def test_addservices_linkkey_lang_searchresults_search_id_filterresults_get(self) -> None:
        """Test case for addservices_linkkey_lang_searchresults_search_id_filterresults_get

        """
        pass

    async def test_get_add_serv_list_result(self) -> None:
        """Test case for get_add_serv_list_result

        List result
        """
        pass

    async def test_get_add_serv_list_result_for_service(self) -> None:
        """Test case for get_add_serv_list_result_for_service

        List result for one service
        """
        pass

    async def test_get_add_serv_list_result_for_service_provider(self) -> None:
        """Test case for get_add_serv_list_result_for_service_provider

        List result for one service provider
        """
        pass

    async def test_get_add_service_product(self) -> None:
        """Test case for get_add_service_product

        Detail of product
        """
        pass

    async def test_get_add_service_products_search_result_for_service(self) -> None:
        """Test case for get_add_service_products_search_result_for_service

        Search result for one service
        """
        pass

    async def test_get_add_service_rating_comments_result(self) -> None:
        """Test case for get_add_service_rating_comments_result

        List of rating comments
        """
        pass

    async def test_get_add_service_service(self) -> None:
        """Test case for get_add_service_service

        Detail of service
        """
        pass

    async def test_get_add_service_service_provider(self) -> None:
        """Test case for get_add_service_service_provider

        Detail of service provider
        """
        pass

    async def test_get_addserv_search_result(self) -> None:
        """Test case for get_addserv_search_result

        Search result
        """
        pass

    async def test_get_addserv_search_result_for_service_provider(self) -> None:
        """Test case for get_addserv_search_result_for_service_provider

        Search result for one service provider
        """
        pass

    async def test_get_linked_events_to_add_service_list_result(self) -> None:
        """Test case for get_linked_events_to_add_service_list_result

        List result of Linked Events
        """
        pass

    async def test_get_linked_infrastructures_to_add_service_result(self) -> None:
        """Test case for get_linked_infrastructures_to_add_service_result

        List result of Linked Infrastructures
        """
        pass

    async def test_get_recommended_add_serv_list_result_for_service(self) -> None:
        """Test case for get_recommended_add_serv_list_result_for_service

        Recommended List result for one service
        """
        pass

    async def test_get_recommended_add_services_search_result_for_service(self) -> None:
        """Test case for get_recommended_add_services_search_result_for_service

        Search result Recommended Services for one service
        """
        pass


if __name__ == '__main__':
    unittest.main()
