# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.api.accommodations_api import AccommodationsApi


class TestAccommodationsApi(unittest.IsolatedAsyncioTestCase):
    """AccommodationsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AccommodationsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_accommodations_linkkey_lang_filterresults_filter_id_get(self) -> None:
        """Test case for accommodations_linkkey_lang_filterresults_filter_id_get

        """
        pass

    async def test_accommodations_linkkey_lang_searchresults_search_id_filterresults_filter_id_get(self) -> None:
        """Test case for accommodations_linkkey_lang_searchresults_search_id_filterresults_filter_id_get

        """
        pass

    async def test_accommodations_linkkey_lang_searchresults_search_id_filterresults_get(self) -> None:
        """Test case for accommodations_linkkey_lang_searchresults_search_id_filterresults_get

        """
        pass

    async def test_get_acc_list_package_result_for_service_provider(self) -> None:
        """Test case for get_acc_list_package_result_for_service_provider

        """
        pass

    async def test_get_acc_list_result_for_service_provider(self) -> None:
        """Test case for get_acc_list_result_for_service_provider

        Detail list of service provider
        """
        pass

    async def test_get_acc_package_search_result_for_service_provider(self) -> None:
        """Test case for get_acc_package_search_result_for_service_provider

        """
        pass

    async def test_get_acc_search_result_for_service_provider(self) -> None:
        """Test case for get_acc_search_result_for_service_provider

        Detail search of service provider
        """
        pass

    async def test_get_acc_service_product(self) -> None:
        """Test case for get_acc_service_product

        Detail of product
        """
        pass

    async def test_get_acc_service_provider(self) -> None:
        """Test case for get_acc_service_provider

        Detail of service provider
        """
        pass

    async def test_get_acco_list_result(self) -> None:
        """Test case for get_acco_list_result

        List result
        """
        pass

    async def test_get_acco_rating_comments_result(self) -> None:
        """Test case for get_acco_rating_comments_result

        List of rating comments
        """
        pass

    async def test_get_acco_search_result(self) -> None:
        """Test case for get_acco_search_result

        """
        pass

    async def test_get_linked_events_to_acco_list_result(self) -> None:
        """Test case for get_linked_events_to_acco_list_result

        List result of Linked Events
        """
        pass

    async def test_get_linked_infrastructures_to_accommodation_result(self) -> None:
        """Test case for get_linked_infrastructures_to_accommodation_result

        List result of Linked Infrastructures
        """
        pass

    async def test_get_price_matrix(self) -> None:
        """Test case for get_price_matrix

        """
        pass


if __name__ == '__main__':
    unittest.main()
