# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.ski_data_delivery_mode_type import SkiDataDeliveryModeType

class TestSkiDataDeliveryModeType(unittest.TestCase):
    """SkiDataDeliveryModeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSkiDataDeliveryModeType(self):
        """Test SkiDataDeliveryModeType"""
        # inst = SkiDataDeliveryModeType()

if __name__ == '__main__':
    unittest.main()
