# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.create_accommodation_detail_request_gateway_command import CreateAccommodationDetailRequestGatewayCommand

class TestCreateAccommodationDetailRequestGatewayCommand(unittest.TestCase):
    """CreateAccommodationDetailRequestGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAccommodationDetailRequestGatewayCommand:
        """Test CreateAccommodationDetailRequestGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAccommodationDetailRequestGatewayCommand`
        """
        model = CreateAccommodationDetailRequestGatewayCommand()
        if include_optional:
            return CreateAccommodationDetailRequestGatewayCommand(
                guest = feratel_client.models.guest_info_create_accommodation_detail_request_gateway_command.GuestInfoCreateAccommodationDetailRequestGatewayCommand(
                    salutation_id = '', 
                    company = '', 
                    first_name = '', 
                    last_name = '', 
                    address = '', 
                    zip_code = '', 
                    town = '', 
                    country_code = '', 
                    phone = '', 
                    fax = '', 
                    e_mail = '', 
                    language = '', 
                    consents = feratel_client.models.guest_consents.GuestConsents(
                        newsletter = True, 
                        marketing = True, 
                        rating = True, ), ),
                message_from_guest = '',
                service_provider_id = '',
                organisation_code = '',
                product_ids = [
                    ''
                    ],
                search_data = feratel_client.models.search_data.SearchData(
                    from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    to_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                occupancy_data = [
                    feratel_client.models.occupancy_data.OccupancyData(
                        units = 56, 
                        adults = 56, 
                        children_ages = [
                            56
                            ], )
                    ],
                meal_type = 0
            )
        else:
            return CreateAccommodationDetailRequestGatewayCommand(
        )
        """

    def testCreateAccommodationDetailRequestGatewayCommand(self):
        """Test CreateAccommodationDetailRequestGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
