# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.add_brochure_item_gateway_command import AddBrochureItemGatewayCommand

class TestAddBrochureItemGatewayCommand(unittest.TestCase):
    """AddBrochureItemGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddBrochureItemGatewayCommand:
        """Test AddBrochureItemGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddBrochureItemGatewayCommand`
        """
        model = AddBrochureItemGatewayCommand()
        if include_optional:
            return AddBrochureItemGatewayCommand(
                item_type = 0,
                product_id = '',
                database_code = '',
                units = 56,
                group_number = 56,
                brochure_id = ''
            )
        else:
            return AddBrochureItemGatewayCommand(
        )
        """

    def testAddBrochureItemGatewayCommand(self):
        """Test AddBrochureItemGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
