# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.request_filter_details_create_accommodation_offer_request_gateway_command import RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand

class TestRequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand(unittest.TestCase):
    """RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand:
        """Test RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand`
        """
        model = RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand()
        if include_optional:
            return RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand(
                accommodation_name = '',
                location_ids = [
                    ''
                    ],
                category_ids = [
                    ''
                    ],
                star_ids = [
                    ''
                    ],
                classification_ids = [
                    ''
                    ],
                service_classification_ids = [
                    ''
                    ],
                marketing_groups = [
                    ''
                    ],
                hotel_chains = [
                    ''
                    ],
                holiday_themes = [
                    ''
                    ],
                features = [
                    ''
                    ],
                service_features = [
                    ''
                    ],
                meal_type = 0,
                price_to = 56
            )
        else:
            return RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand(
        )
        """

    def testRequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand(self):
        """Test RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
