# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.payment_provider_type import PaymentProviderType

class TestPaymentProviderType(unittest.TestCase):
    """PaymentProviderType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentProviderType(self):
        """Test PaymentProviderType"""
        # inst = PaymentProviderType()

if __name__ == '__main__':
    unittest.main()
