# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.update_checkout_question_gateway_command import UpdateCheckoutQuestionGatewayCommand

class TestUpdateCheckoutQuestionGatewayCommand(unittest.TestCase):
    """UpdateCheckoutQuestionGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCheckoutQuestionGatewayCommand:
        """Test UpdateCheckoutQuestionGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCheckoutQuestionGatewayCommand`
        """
        model = UpdateCheckoutQuestionGatewayCommand()
        if include_optional:
            return UpdateCheckoutQuestionGatewayCommand(
                id = '',
                unique_id = '',
                command_type = 0,
                answer = None
            )
        else:
            return UpdateCheckoutQuestionGatewayCommand(
        )
        """

    def testUpdateCheckoutQuestionGatewayCommand(self):
        """Test UpdateCheckoutQuestionGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
