# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.shopping_list_bulk_add_items_to_shopping_list_gateway_command import ShoppingListBulkAddItemsToShoppingListGatewayCommand

class TestShoppingListBulkAddItemsToShoppingListGatewayCommand(unittest.TestCase):
    """ShoppingListBulkAddItemsToShoppingListGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShoppingListBulkAddItemsToShoppingListGatewayCommand:
        """Test ShoppingListBulkAddItemsToShoppingListGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShoppingListBulkAddItemsToShoppingListGatewayCommand`
        """
        model = ShoppingListBulkAddItemsToShoppingListGatewayCommand()
        if include_optional:
            return ShoppingListBulkAddItemsToShoppingListGatewayCommand(
                add_service_items = [
                    feratel_client.models.shopping_list_add_additional_service_item_gateway_command.ShoppingListAddAdditionalServiceItemGatewayCommand(
                        item_type = 0, 
                        product_group_id = '', 
                        sales_point_id = '', 
                        product_id = '', 
                        database_code = '', 
                        units = 56, 
                        group_number = 56, 
                        arrival_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        starting_time = '', 
                        duration_value = 56, 
                        price_overrides = feratel_client.models.add_service_price_overrides.AddServicePriceOverrides(
                            currency = '', 
                            price = 1.337, ), )
                    ],
                accommodation_items = [
                    feratel_client.models.shopping_list_add_accommodation_item_gateway_command.ShoppingListAddAccommodationItemGatewayCommand(
                        item_type = 0, 
                        product_id = '', 
                        database_code = '', 
                        units = 56, 
                        group_number = 56, 
                        arrival_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        departure_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        adults = 56, 
                        children_ages = [
                            56
                            ], 
                        meal_type = 0, )
                    ],
                brochure_items = [
                    feratel_client.models.shopping_list_add_brochure_item_gateway_command.ShoppingListAddBrochureItemGatewayCommand(
                        item_type = 0, 
                        product_id = '', 
                        database_code = '', 
                        units = 56, 
                        group_number = 56, 
                        brochure_id = '', )
                    ],
                package_items = [
                    feratel_client.models.shopping_list_add_package_item_gateway_command.ShoppingListAddPackageItemGatewayCommand(
                        item_type = 0, 
                        product_id = '', 
                        database_code = '', 
                        units = 56, 
                        group_number = 56, 
                        arrival_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        duration = 56, 
                        adults = 56, 
                        category_id = '', 
                        children_ages = [
                            56
                            ], 
                        meal_type = 0, 
                        sections = [
                            feratel_client.models.add_package_section_item_command.AddPackageSectionItemCommand(
                                section_id = '', 
                                date_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                duration = 56, 
                                adults = 56, 
                                units = 56, 
                                product_id = '', )
                            ], )
                    ],
                tour_items = [
                    feratel_client.models.shopping_list_add_tour_item_gateway_command.ShoppingListAddTourItemGatewayCommand(
                        item_type = 0, 
                        product_group_id = '', 
                        sales_point_id = '', 
                        product_id = '', 
                        database_code = '', 
                        units = 56, 
                        group_number = 56, 
                        tour_id = '', 
                        arrival_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        starting_time = '', 
                        duration_value = 56, 
                        language = '', 
                        people = 56, )
                    ]
            )
        else:
            return ShoppingListBulkAddItemsToShoppingListGatewayCommand(
        )
        """

    def testShoppingListBulkAddItemsToShoppingListGatewayCommand(self):
        """Test ShoppingListBulkAddItemsToShoppingListGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
