# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.add_additional_service_item_gateway_command import AddAdditionalServiceItemGatewayCommand

class TestAddAdditionalServiceItemGatewayCommand(unittest.TestCase):
    """AddAdditionalServiceItemGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddAdditionalServiceItemGatewayCommand:
        """Test AddAdditionalServiceItemGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddAdditionalServiceItemGatewayCommand`
        """
        model = AddAdditionalServiceItemGatewayCommand()
        if include_optional:
            return AddAdditionalServiceItemGatewayCommand(
                item_type = 0,
                product_id = '',
                database_code = '',
                units = 56,
                group_number = 56,
                arrival_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                starting_time = '',
                duration_value = 56,
                linked_data = feratel_client.models.add_item_linked_data_gateway_command.AddItemLinkedDataGatewayCommand(
                    link_type = 0, 
                    parent_type = 0, 
                    parent_id = '', ),
                price_overrides = feratel_client.models.add_service_price_overrides.AddServicePriceOverrides(
                    currency = '', 
                    price = 1.337, )
            )
        else:
            return AddAdditionalServiceItemGatewayCommand(
        )
        """

    def testAddAdditionalServiceItemGatewayCommand(self):
        """Test AddAdditionalServiceItemGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
