# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.api.convert_api import ConvertApi


class TestConvertApi(unittest.IsolatedAsyncioTestCase):
    """ConvertApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ConvertApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_convert_convert_offer_post(self) -> None:
        """Test case for convert_convert_offer_post

        """
        pass

    async def test_convert_convert_sp_offer_post(self) -> None:
        """Test case for convert_convert_sp_offer_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
