# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.api.shopping_cart_api import ShoppingCartApi


class TestShoppingCartApi(unittest.IsolatedAsyncioTestCase):
    """ShoppingCartApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ShoppingCartApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_shopping_cart_detail(self) -> None:
        """Test case for get_shopping_cart_detail

        Detail of ShoppingCart
        """
        pass

    async def test_get_shopping_cart_electronic_payment(self) -> None:
        """Test case for get_shopping_cart_electronic_payment

        """
        pass

    async def test_get_shopping_cart_recommended_services(self) -> None:
        """Test case for get_shopping_cart_recommended_services

        """
        pass

    async def test_shopping_cart_confirmation(self) -> None:
        """Test case for shopping_cart_confirmation

        Get ShoppingCart Confirmation
        """
        pass

    async def test_shopping_cart_payment_texts(self) -> None:
        """Test case for shopping_cart_payment_texts

        Get ShoppingCart Payment Texts
        """
        pass

    async def test_shoppingcart_linkkey_lang_id_book_post(self) -> None:
        """Test case for shoppingcart_linkkey_lang_id_book_post

        """
        pass

    async def test_shoppingcart_linkkey_lang_id_delete(self) -> None:
        """Test case for shoppingcart_linkkey_lang_id_delete

        """
        pass

    async def test_shoppingcart_linkkey_lang_id_discountcodes_code_post(self) -> None:
        """Test case for shoppingcart_linkkey_lang_id_discountcodes_code_post

        """
        pass

    async def test_shoppingcart_linkkey_lang_id_guest_put(self) -> None:
        """Test case for shoppingcart_linkkey_lang_id_guest_put

        """
        pass

    async def test_shoppingcart_linkkey_lang_id_items_add_post(self) -> None:
        """Test case for shoppingcart_linkkey_lang_id_items_add_post

        """
        pass

    async def test_shoppingcart_linkkey_lang_id_items_addserviceaddon_post(self) -> None:
        """Test case for shoppingcart_linkkey_lang_id_items_addserviceaddon_post

        """
        pass

    async def test_shoppingcart_linkkey_lang_id_payment_put(self) -> None:
        """Test case for shoppingcart_linkkey_lang_id_payment_put

        """
        pass

    async def test_shoppingcart_linkkey_lang_id_unlock_put(self) -> None:
        """Test case for shoppingcart_linkkey_lang_id_unlock_put

        """
        pass

    async def test_shoppingcart_linkkey_lang_post(self) -> None:
        """Test case for shoppingcart_linkkey_lang_post

        """
        pass

    async def test_shoppingcart_linkkey_lang_shopping_cart_id_discountcodes_code_delete(self) -> None:
        """Test case for shoppingcart_linkkey_lang_shopping_cart_id_discountcodes_code_delete

        """
        pass

    async def test_shoppingcart_linkkey_lang_shopping_cart_id_items_accommodations_item_id_put(self) -> None:
        """Test case for shoppingcart_linkkey_lang_shopping_cart_id_items_accommodations_item_id_put

        """
        pass

    async def test_shoppingcart_linkkey_lang_shopping_cart_id_items_addservices_item_id_put(self) -> None:
        """Test case for shoppingcart_linkkey_lang_shopping_cart_id_items_addservices_item_id_put

        """
        pass

    async def test_shoppingcart_linkkey_lang_shopping_cart_id_items_brochures_item_id_put(self) -> None:
        """Test case for shoppingcart_linkkey_lang_shopping_cart_id_items_brochures_item_id_put

        """
        pass

    async def test_shoppingcart_linkkey_lang_shopping_cart_id_items_item_id_delete(self) -> None:
        """Test case for shoppingcart_linkkey_lang_shopping_cart_id_items_item_id_delete

        """
        pass

    async def test_shoppingcart_linkkey_lang_shopping_cart_id_items_tours_item_id_put(self) -> None:
        """Test case for shoppingcart_linkkey_lang_shopping_cart_id_items_tours_item_id_put

        """
        pass

    async def test_shoppingcart_linkkey_lang_validateswisspass_post(self) -> None:
        """Test case for shoppingcart_linkkey_lang_validateswisspass_post

        """
        pass

    async def test_validate_shopping_cart(self) -> None:
        """Test case for validate_shopping_cart

        Validate shopping cart if it is ok to continue to booking
        """
        pass


if __name__ == '__main__':
    unittest.main()
