# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.api.brochures_api import BrochuresApi


class TestBrochuresApi(unittest.IsolatedAsyncioTestCase):
    """BrochuresApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = BrochuresApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_brochures_linkkey_lang_filterresults_filter_id_get(self) -> None:
        """Test case for brochures_linkkey_lang_filterresults_filter_id_get

        """
        pass

    async def test_brochures_linkkey_lang_filterresults_get(self) -> None:
        """Test case for brochures_linkkey_lang_filterresults_get

        """
        pass

    async def test_get_brochure_detail_result(self) -> None:
        """Test case for get_brochure_detail_result

        Detail of brochure
        """
        pass

    async def test_get_brochure_list_result(self) -> None:
        """Test case for get_brochure_list_result

        List result
        """
        pass


if __name__ == '__main__':
    unittest.main()
