# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.search_package import SearchPackage

class TestSearchPackage(unittest.TestCase):
    """SearchPackage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchPackage:
        """Test SearchPackage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchPackage`
        """
        model = SearchPackage()
        if include_optional:
            return SearchPackage(
                adults = 56,
                children = 56,
                children_ages = [
                    56
                    ],
                duration = 56,
                category_id = ''
            )
        else:
            return SearchPackage(
        )
        """

    def testSearchPackage(self):
        """Test SearchPackage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
