# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.api.shopping_list_api import ShoppingListApi


class TestShoppingListApi(unittest.IsolatedAsyncioTestCase):
    """ShoppingListApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ShoppingListApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_shopping_list_detail(self) -> None:
        """Test case for get_shopping_list_detail

        Detail of ShoppingList
        """
        pass

    async def test_shoppinglist_linkkey_id_carts_cart_id_delete(self) -> None:
        """Test case for shoppinglist_linkkey_id_carts_cart_id_delete

        """
        pass

    async def test_shoppinglist_linkkey_id_delete(self) -> None:
        """Test case for shoppinglist_linkkey_id_delete

        """
        pass

    async def test_shoppinglist_linkkey_id_items_add_post(self) -> None:
        """Test case for shoppinglist_linkkey_id_items_add_post

        """
        pass

    async def test_shoppinglist_linkkey_post(self) -> None:
        """Test case for shoppinglist_linkkey_post

        """
        pass

    async def test_shoppinglist_linkkey_shopping_list_id_items_item_id_delete(self) -> None:
        """Test case for shoppinglist_linkkey_shopping_list_id_items_item_id_delete

        """
        pass


if __name__ == '__main__':
    unittest.main()
