# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.api.click_count_api import ClickCountApi


class TestClickCountApi(unittest.IsolatedAsyncioTestCase):
    """ClickCountApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ClickCountApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_clickcount_linkkey_post(self) -> None:
        """Test case for clickcount_linkkey_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
