# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.calculate_org_package_price_gateway_command import CalculateOrgPackagePriceGatewayCommand

class TestCalculateOrgPackagePriceGatewayCommand(unittest.TestCase):
    """CalculateOrgPackagePriceGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CalculateOrgPackagePriceGatewayCommand:
        """Test CalculateOrgPackagePriceGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CalculateOrgPackagePriceGatewayCommand`
        """
        model = CalculateOrgPackagePriceGatewayCommand()
        if include_optional:
            return CalculateOrgPackagePriceGatewayCommand(
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                duration = 56,
                category_id = '',
                adults = 56,
                children_ages = '',
                currency_code = '',
                sections = [
                    feratel_client.models.section.Section(
                        section_id = '', 
                        product_id = '', 
                        date_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        add_nights = 56, 
                        adults = 56, 
                        children_ages = [
                            feratel_client.models.section_children_age.SectionChildrenAge(
                                age = 56, 
                                units = 56, )
                            ], 
                        units = 56, )
                    ]
            )
        else:
            return CalculateOrgPackagePriceGatewayCommand(
        )
        """

    def testCalculateOrgPackagePriceGatewayCommand(self):
        """Test CalculateOrgPackagePriceGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
