# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.add_package_section_item_command import AddPackageSectionItemCommand

class TestAddPackageSectionItemCommand(unittest.TestCase):
    """AddPackageSectionItemCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddPackageSectionItemCommand:
        """Test AddPackageSectionItemCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddPackageSectionItemCommand`
        """
        model = AddPackageSectionItemCommand()
        if include_optional:
            return AddPackageSectionItemCommand(
                section_id = '',
                item_type = 0,
                date_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                duration = 56,
                adults = 56,
                children_ages = [
                    feratel_client.models.add_package_section_item_child_ages_command.AddPackageSectionItemChildAgesCommand(
                        age = 56, 
                        units = 56, )
                    ],
                units = 56,
                product_id = ''
            )
        else:
            return AddPackageSectionItemCommand(
        )
        """

    def testAddPackageSectionItemCommand(self):
        """Test AddPackageSectionItemCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
