# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.search_accommodation import SearchAccommodation

class TestSearchAccommodation(unittest.TestCase):
    """SearchAccommodation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchAccommodation:
        """Test SearchAccommodation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchAccommodation`
        """
        model = SearchAccommodation()
        if include_optional:
            return SearchAccommodation(
                bookable_only = True,
                search_lines = [
                    feratel_client.models.search_line.SearchLine(
                        units = 56, 
                        adults = 56, 
                        children = 56, 
                        children_ages = [
                            56
                            ], )
                    ],
                meal = 0
            )
        else:
            return SearchAccommodation(
        )
        """

    def testSearchAccommodation(self):
        """Test SearchAccommodation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
