# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.guest_consents import GuestConsents

class TestGuestConsents(unittest.TestCase):
    """GuestConsents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GuestConsents:
        """Test GuestConsents
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GuestConsents`
        """
        model = GuestConsents()
        if include_optional:
            return GuestConsents(
                newsletter = True,
                marketing = True,
                rating = True
            )
        else:
            return GuestConsents(
        )
        """

    def testGuestConsents(self):
        """Test GuestConsents"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
