# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.feratel_guest_card_item import FeratelGuestCardItem

class TestFeratelGuestCardItem(unittest.TestCase):
    """FeratelGuestCardItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeratelGuestCardItem:
        """Test FeratelGuestCardItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeratelGuestCardItem`
        """
        model = FeratelGuestCardItem()
        if include_optional:
            return FeratelGuestCardItem(
                item_id = '',
                card_process_mode = 0,
                card_input_data = feratel_client.models.feratel_guest_card_input_data.FeratelGuestCardInputData(
                    card_number = '', ),
                person = feratel_client.models.external_person_information_data.ExternalPersonInformationData(
                    guest_portal_user_id = '', 
                    title = 100, 
                    first_name = '', 
                    last_name = '', 
                    date_of_birth = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    picture = '', )
            )
        else:
            return FeratelGuestCardItem(
        )
        """

    def testFeratelGuestCardItem(self):
        """Test FeratelGuestCardItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
