# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.axess_delivery_mode_type import AxessDeliveryModeType

class TestAxessDeliveryModeType(unittest.TestCase):
    """AxessDeliveryModeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAxessDeliveryModeType(self):
        """Test AxessDeliveryModeType"""
        # inst = AxessDeliveryModeType()

if __name__ == '__main__':
    unittest.main()
