# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.section_children_age import SectionChildrenAge

class TestSectionChildrenAge(unittest.TestCase):
    """SectionChildrenAge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SectionChildrenAge:
        """Test SectionChildrenAge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SectionChildrenAge`
        """
        model = SectionChildrenAge()
        if include_optional:
            return SectionChildrenAge(
                age = 56,
                units = 56
            )
        else:
            return SectionChildrenAge(
        )
        """

    def testSectionChildrenAge(self):
        """Test SectionChildrenAge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
