# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.shopping_list_add_package_item_gateway_command import ShoppingListAddPackageItemGatewayCommand

class TestShoppingListAddPackageItemGatewayCommand(unittest.TestCase):
    """ShoppingListAddPackageItemGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShoppingListAddPackageItemGatewayCommand:
        """Test ShoppingListAddPackageItemGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShoppingListAddPackageItemGatewayCommand`
        """
        model = ShoppingListAddPackageItemGatewayCommand()
        if include_optional:
            return ShoppingListAddPackageItemGatewayCommand(
                item_type = 0,
                product_id = '',
                database_code = '',
                units = 56,
                group_number = 56,
                arrival_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                duration = 56,
                adults = 56,
                category_id = '',
                children_ages = [
                    56
                    ],
                meal_type = 0,
                sections = [
                    feratel_client.models.add_package_section_item_command.AddPackageSectionItemCommand(
                        section_id = '', 
                        item_type = 0, 
                        date_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        duration = 56, 
                        adults = 56, 
                        children_ages = [
                            feratel_client.models.add_package_section_item_child_ages_command.AddPackageSectionItemChildAgesCommand(
                                age = 56, 
                                units = 56, )
                            ], 
                        units = 56, 
                        product_id = '', )
                    ]
            )
        else:
            return ShoppingListAddPackageItemGatewayCommand(
        )
        """

    def testShoppingListAddPackageItemGatewayCommand(self):
        """Test ShoppingListAddPackageItemGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
