# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.occupancy_data import OccupancyData

class TestOccupancyData(unittest.TestCase):
    """OccupancyData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OccupancyData:
        """Test OccupancyData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OccupancyData`
        """
        model = OccupancyData()
        if include_optional:
            return OccupancyData(
                units = 56,
                adults = 56,
                children_ages = [
                    56
                    ]
            )
        else:
            return OccupancyData(
        )
        """

    def testOccupancyData(self):
        """Test OccupancyData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
