# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.request_pool_communication_type import RequestPoolCommunicationType

class TestRequestPoolCommunicationType(unittest.TestCase):
    """RequestPoolCommunicationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestPoolCommunicationType(self):
        """Test RequestPoolCommunicationType"""
        # inst = RequestPoolCommunicationType()

if __name__ == '__main__':
    unittest.main()
