# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.swiss_pass_data import SwissPassData

class TestSwissPassData(unittest.TestCase):
    """SwissPassData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwissPassData:
        """Test SwissPassData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwissPassData`
        """
        model = SwissPassData()
        if include_optional:
            return SwissPassData(
                swiss_pass_id = '',
                zip_code = ''
            )
        else:
            return SwissPassData(
        )
        """

    def testSwissPassData(self):
        """Test SwissPassData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
