# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.axess_ticket_item import AxessTicketItem

class TestAxessTicketItem(unittest.TestCase):
    """AxessTicketItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AxessTicketItem:
        """Test AxessTicketItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AxessTicketItem`
        """
        model = AxessTicketItem()
        if include_optional:
            return AxessTicketItem(
                id = '',
                item_id = '',
                mode = 1,
                person = feratel_client.models.external_person_information_data.ExternalPersonInformationData(
                    guest_portal_user_id = '', 
                    title = 100, 
                    first_name = '', 
                    last_name = '', 
                    date_of_birth = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    picture = '', ),
                axess_input_data = feratel_client.models.axess_ticket_input_data.AxessTicketInputData(
                    card_number = '', 
                    selected_delivery_mode = 0, ),
                swiss_pass_data = feratel_client.models.swiss_pass_data.SwissPassData(
                    swiss_pass_id = '', 
                    zip_code = '', )
            )
        else:
            return AxessTicketItem(
        )
        """

    def testAxessTicketItem(self):
        """Test AxessTicketItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
