# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.price_filter import PriceFilter

class TestPriceFilter(unittest.TestCase):
    """PriceFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PriceFilter:
        """Test PriceFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PriceFilter`
        """
        model = PriceFilter()
        if include_optional:
            return PriceFilter(
                var_from = 1.337,
                to = 1.337
            )
        else:
            return PriceFilter(
        )
        """

    def testPriceFilter(self):
        """Test PriceFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
