# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.external_person_information_data import ExternalPersonInformationData

class TestExternalPersonInformationData(unittest.TestCase):
    """ExternalPersonInformationData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalPersonInformationData:
        """Test ExternalPersonInformationData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalPersonInformationData`
        """
        model = ExternalPersonInformationData()
        if include_optional:
            return ExternalPersonInformationData(
                guest_portal_user_id = '',
                title = 100,
                first_name = '',
                last_name = '',
                date_of_birth = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                picture = ''
            )
        else:
            return ExternalPersonInformationData(
        )
        """

    def testExternalPersonInformationData(self):
        """Test ExternalPersonInformationData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
