# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.add_package_section_item_child_ages_command import AddPackageSectionItemChildAgesCommand

class TestAddPackageSectionItemChildAgesCommand(unittest.TestCase):
    """AddPackageSectionItemChildAgesCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddPackageSectionItemChildAgesCommand:
        """Test AddPackageSectionItemChildAgesCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddPackageSectionItemChildAgesCommand`
        """
        model = AddPackageSectionItemChildAgesCommand()
        if include_optional:
            return AddPackageSectionItemChildAgesCommand(
                age = 56,
                units = 56
            )
        else:
            return AddPackageSectionItemChildAgesCommand(
        )
        """

    def testAddPackageSectionItemChildAgesCommand(self):
        """Test AddPackageSectionItemChildAgesCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
