# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.create_add_service_offer_request_gateway_command import CreateAddServiceOfferRequestGatewayCommand

class TestCreateAddServiceOfferRequestGatewayCommand(unittest.TestCase):
    """CreateAddServiceOfferRequestGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAddServiceOfferRequestGatewayCommand:
        """Test CreateAddServiceOfferRequestGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAddServiceOfferRequestGatewayCommand`
        """
        model = CreateAddServiceOfferRequestGatewayCommand()
        if include_optional:
            return CreateAddServiceOfferRequestGatewayCommand(
                parent_type = 0,
                search_data = feratel_client.models.search_data.SearchData(
                    from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    to_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                guest = feratel_client.models.guest_info_create_add_service_offer_request_gateway_command.GuestInfoCreateAddServiceOfferRequestGatewayCommand(
                    salutation_id = '', 
                    company = '', 
                    first_name = '', 
                    last_name = '', 
                    address = '', 
                    zip_code = '', 
                    town = '', 
                    country_code = '', 
                    phone = '', 
                    mobile = '', 
                    fax = '', 
                    e_mail = '', 
                    language = '', 
                    consents = feratel_client.models.guest_consents.GuestConsents(
                        newsletter = True, 
                        marketing = True, 
                        rating = True, ), ),
                filter_details = feratel_client.models.request_filter_additional_service_details.RequestFilterAdditionalServiceDetails(
                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    start_time = '', 
                    duration = 56, 
                    duration_type = 0, 
                    units = 56, ),
                message = '',
                currency_code = ''
            )
        else:
            return CreateAddServiceOfferRequestGatewayCommand(
        )
        """

    def testCreateAddServiceOfferRequestGatewayCommand(self):
        """Test CreateAddServiceOfferRequestGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
