# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.create_click_count_gateway_command import CreateClickCountGatewayCommand

class TestCreateClickCountGatewayCommand(unittest.TestCase):
    """CreateClickCountGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateClickCountGatewayCommand:
        """Test CreateClickCountGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateClickCountGatewayCommand`
        """
        model = CreateClickCountGatewayCommand()
        if include_optional:
            return CreateClickCountGatewayCommand(
                db_code = '0',
                click_count_type = 0,
                parent_id = '',
                session_id = '0'
            )
        else:
            return CreateClickCountGatewayCommand(
                db_code = '0',
                click_count_type = 0,
                parent_id = '',
                session_id = '0',
        )
        """

    def testCreateClickCountGatewayCommand(self):
        """Test CreateClickCountGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
