# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.additional_service_age_restriction import AdditionalServiceAgeRestriction

class TestAdditionalServiceAgeRestriction(unittest.TestCase):
    """AdditionalServiceAgeRestriction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdditionalServiceAgeRestriction:
        """Test AdditionalServiceAgeRestriction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdditionalServiceAgeRestriction`
        """
        model = AdditionalServiceAgeRestriction()
        if include_optional:
            return AdditionalServiceAgeRestriction(
                has_age_restriction = True,
                use_age = True,
                var_from = 56,
                to = 56,
                values = [
                    56
                    ]
            )
        else:
            return AdditionalServiceAgeRestriction(
        )
        """

    def testAdditionalServiceAgeRestriction(self):
        """Test AdditionalServiceAgeRestriction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
