# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.add_service_price_overrides import AddServicePriceOverrides

class TestAddServicePriceOverrides(unittest.TestCase):
    """AddServicePriceOverrides unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddServicePriceOverrides:
        """Test AddServicePriceOverrides
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddServicePriceOverrides`
        """
        model = AddServicePriceOverrides()
        if include_optional:
            return AddServicePriceOverrides(
                currency = '',
                price = 1.337
            )
        else:
            return AddServicePriceOverrides(
        )
        """

    def testAddServicePriceOverrides(self):
        """Test AddServicePriceOverrides"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
