# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.create_search_object_ds_api import CreateSearchObjectDSApi

class TestCreateSearchObjectDSApi(unittest.TestCase):
    """CreateSearchObjectDSApi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSearchObjectDSApi:
        """Test CreateSearchObjectDSApi
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSearchObjectDSApi`
        """
        model = CreateSearchObjectDSApi()
        if include_optional:
            return CreateSearchObjectDSApi(
                search_general = feratel_client.models.search_general.SearchGeneral(
                    date_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    date_to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    days = 56, 
                    nights = 56, ),
                search_accommodation = feratel_client.models.search_accommodation.SearchAccommodation(
                    bookable_only = True, 
                    search_lines = [
                        feratel_client.models.search_line.SearchLine(
                            units = 56, 
                            adults = 56, 
                            children = 56, 
                            children_ages = [
                                56
                                ], )
                        ], 
                    meal = 0, ),
                search_add_service = feratel_client.models.search_add_services.SearchAddServices(
                    bookable_only = True, 
                    service_providers = [
                        ''
                        ], 
                    services = [
                        ''
                        ], 
                    products = [
                        ''
                        ], 
                    org_package_assignments_occupancy = feratel_client.models.org_package_assignments_occupancy.OrgPackageAssignmentsOccupancy(
                        units = 56, 
                        adults = 56, 
                        children = 56, 
                        children_ages = [
                            56
                            ], ), ),
                search_package = feratel_client.models.search_package.SearchPackage(
                    adults = 56, 
                    children = 56, 
                    children_ages = [
                        56
                        ], 
                    duration = 56, 
                    category_id = '', )
            )
        else:
            return CreateSearchObjectDSApi(
        )
        """

    def testCreateSearchObjectDSApi(self):
        """Test CreateSearchObjectDSApi"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
