# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.add_accommodation_item_gateway_command import AddAccommodationItemGatewayCommand

class TestAddAccommodationItemGatewayCommand(unittest.TestCase):
    """AddAccommodationItemGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddAccommodationItemGatewayCommand:
        """Test AddAccommodationItemGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddAccommodationItemGatewayCommand`
        """
        model = AddAccommodationItemGatewayCommand()
        if include_optional:
            return AddAccommodationItemGatewayCommand(
                item_type = 0,
                product_id = '',
                database_code = '',
                units = 56,
                group_number = 56,
                arrival_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                departure_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                adults = 56,
                meal_type = 0
            )
        else:
            return AddAccommodationItemGatewayCommand(
        )
        """

    def testAddAccommodationItemGatewayCommand(self):
        """Test AddAccommodationItemGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
