# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.cart_item_link_type import CartItemLinkType

class TestCartItemLinkType(unittest.TestCase):
    """CartItemLinkType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCartItemLinkType(self):
        """Test CartItemLinkType"""
        # inst = CartItemLinkType()

if __name__ == '__main__':
    unittest.main()
