# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.update_shopping_cart_payment_data_command import UpdateShoppingCartPaymentDataCommand

class TestUpdateShoppingCartPaymentDataCommand(unittest.TestCase):
    """UpdateShoppingCartPaymentDataCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateShoppingCartPaymentDataCommand:
        """Test UpdateShoppingCartPaymentDataCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateShoppingCartPaymentDataCommand`
        """
        model = UpdateShoppingCartPaymentDataCommand()
        if include_optional:
            return UpdateShoppingCartPaymentDataCommand(
                use_optional_cancellation_insurance = True,
                selected_payment_provider = 0,
                selected_payment_action = 0
            )
        else:
            return UpdateShoppingCartPaymentDataCommand(
        )
        """

    def testUpdateShoppingCartPaymentDataCommand(self):
        """Test UpdateShoppingCartPaymentDataCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
