# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.api.events_api import EventsApi


class TestEventsApi(unittest.IsolatedAsyncioTestCase):
    """EventsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = EventsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_events_linkkey_lang_filterresults_filter_id_get(self) -> None:
        """Test case for events_linkkey_lang_filterresults_filter_id_get

        """
        pass

    async def test_events_linkkey_lang_searchresults_search_id_filterresults_filter_id_get(self) -> None:
        """Test case for events_linkkey_lang_searchresults_search_id_filterresults_filter_id_get

        """
        pass

    async def test_get_detail_result(self) -> None:
        """Test case for get_detail_result

        Detail of event
        """
        pass

    async def test_get_event_list_result(self) -> None:
        """Test case for get_event_list_result

        List result
        """
        pass

    async def test_get_event_search_result(self) -> None:
        """Test case for get_event_search_result

        Search result
        """
        pass

    async def test_get_group_detail_result(self) -> None:
        """Test case for get_group_detail_result

        Event group details
        """
        pass

    async def test_get_linked_add_serv_list_result(self) -> None:
        """Test case for get_linked_add_serv_list_result

        List result of Linked Add. Services
        """
        pass

    async def test_get_linked_events_result(self) -> None:
        """Test case for get_linked_events_result

        List result of Linked event from link infrastructures
        """
        pass

    async def test_get_linked_infrastructures_result(self) -> None:
        """Test case for get_linked_infrastructures_result

        List result of Linked Infrastructures
        """
        pass


if __name__ == '__main__':
    unittest.main()
