# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.ski_data_package_input_data import SkiDataPackageInputData

class TestSkiDataPackageInputData(unittest.TestCase):
    """SkiDataPackageInputData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SkiDataPackageInputData:
        """Test SkiDataPackageInputData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SkiDataPackageInputData`
        """
        model = SkiDataPackageInputData()
        if include_optional:
            return SkiDataPackageInputData(
                ticket_delivery_mode = 0,
                mode = 1
            )
        else:
            return SkiDataPackageInputData(
        )
        """

    def testSkiDataPackageInputData(self):
        """Test SkiDataPackageInputData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
