# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.ski_data_process_mode import SkiDataProcessMode

class TestSkiDataProcessMode(unittest.TestCase):
    """SkiDataProcessMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSkiDataProcessMode(self):
        """Test SkiDataProcessMode"""
        # inst = SkiDataProcessMode()

if __name__ == '__main__':
    unittest.main()
