# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from feratel_client.models.update_additional_service_item_gateway_command import UpdateAdditionalServiceItemGatewayCommand

class TestUpdateAdditionalServiceItemGatewayCommand(unittest.TestCase):
    """UpdateAdditionalServiceItemGatewayCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAdditionalServiceItemGatewayCommand:
        """Test UpdateAdditionalServiceItemGatewayCommand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAdditionalServiceItemGatewayCommand`
        """
        model = UpdateAdditionalServiceItemGatewayCommand()
        if include_optional:
            return UpdateAdditionalServiceItemGatewayCommand(
                units = 56,
                external_system_data = feratel_client.models.update_add_service_external_data.UpdateAddServiceExternalData(
                    ski_data = [
                        feratel_client.models.ski_data_ticket_item.SkiDataTicketItem(
                            id = '', 
                            item_id = '', 
                            mode = 1, 
                            person = feratel_client.models.external_person_information_data.ExternalPersonInformationData(
                                guest_portal_user_id = '', 
                                title = 100, 
                                first_name = '', 
                                last_name = '', 
                                date_of_birth = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                picture = '', ), 
                            ski_data_input_data = feratel_client.models.ski_data_input_data.SkiDataInputData(
                                chip_id = '', 
                                serial_number = '', 
                                luhn = '', 
                                picture = '', 
                                selected_delivery_mode = 0, ), 
                            swiss_pass_data = feratel_client.models.swiss_pass_data.SwissPassData(
                                swiss_pass_id = '', 
                                zip_code = '', ), )
                        ], 
                    ski_data_package = feratel_client.models.update_ski_data_package_data.UpdateSkiDataPackageData(
                        package_input_data = feratel_client.models.ski_data_package_input_data.SkiDataPackageInputData(
                            ticket_delivery_mode = 0, ), 
                        ticket_items = [
                            feratel_client.models.ski_data_package_item.SkiDataPackageItem(
                                id = '', 
                                item_id = '', 
                                service_id = '', 
                                type = 0, 
                                deposit_fee_product_id = '', 
                                age_restriction = feratel_client.models.additional_service_age_restriction.AdditionalServiceAgeRestriction(
                                    has_age_restriction = True, 
                                    use_age = True, 
                                    from = 56, 
                                    to = 56, 
                                    values = [
                                        56
                                        ], ), 
                                white_list = [
                                    ''
                                    ], 
                                black_list = [
                                    ''
                                    ], )
                            ], ), 
                    feratel_guest_card = [
                        feratel_client.models.feratel_guest_card_item.FeratelGuestCardItem(
                            item_id = '', 
                            card_process_mode = 0, 
                            card_input_data = feratel_client.models.feratel_guest_card_input_data.FeratelGuestCardInputData(
                                card_number = '', ), )
                        ], 
                    rentmaxx_person_data = feratel_client.models.external_person_information_data.ExternalPersonInformationData(
                        guest_portal_user_id = '', 
                        first_name = '', 
                        last_name = '', 
                        date_of_birth = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        picture = '', ), 
                    waldhart_selection = feratel_client.models.waldhart_selection.WaldhartSelection(
                        attribute_id = 56, 
                        language_code = '', 
                        duration_type = 56, 
                        quantity = 56, 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        lesson_time_id = 56, 
                        sport_selection = 56, 
                        level_selection = 56, 
                        meeting_point_selection = 56, 
                        execution_day_id = 56, 
                        number_of_persons = 56, ), 
                    voucher = feratel_client.models.voucher_data.VoucherData(
                        recipient_name = '', 
                        voucher_text = '', 
                        image_id = '', ), 
                    axess = [
                        feratel_client.models.axess_ticket_item.AxessTicketItem(
                            id = '', 
                            item_id = '', 
                            axess_input_data = feratel_client.models.axess_ticket_input_data.AxessTicketInputData(
                                card_number = '', ), )
                        ], ),
                checkout_questions = [
                    feratel_client.models.update_checkout_question_gateway_command.UpdateCheckoutQuestionGatewayCommand(
                        id = '', 
                        unique_id = '', 
                        command_type = 0, 
                        answer = null, )
                    ],
                children_ages = [
                    56
                    ]
            )
        else:
            return UpdateAdditionalServiceItemGatewayCommand(
        )
        """

    def testUpdateAdditionalServiceItemGatewayCommand(self):
        """Test UpdateAdditionalServiceItemGatewayCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
