# coding: utf-8

# flake8: noqa

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccommodationsApi",
    "AddServicesApi",
    "AuthApi",
    "BrochuresApi",
    "ClickCountApi",
    "ConvertApi",
    "EventsApi",
    "FiltersApi",
    "InfrastructuresApi",
    "KeyValuesApi",
    "PackagesApi",
    "RequestsApi",
    "SearchesApi",
    "ShoppingCartApi",
    "ShoppingListApi",
    "ToursApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddAccommodationItemGatewayCommand",
    "AddAdditionalServiceItemGatewayCommand",
    "AddArticleItemGatewayCommand",
    "AddBrochureItemGatewayCommand",
    "AddItemLinkedDataGatewayCommand",
    "AddPackageItemGatewayCommand",
    "AddPackageSectionItemChildAgesCommand",
    "AddPackageSectionItemCommand",
    "AddRecommendedAddonItemGatewayCommand",
    "AddServicePriceOverrides",
    "AddTourItemGatewayCommand",
    "AdditionalServiceAgeRestriction",
    "ArrivingGuest",
    "AxessDeliveryModeType",
    "AxessProcessMode",
    "AxessTicketInputData",
    "AxessTicketItem",
    "BulkAddItemsToCartGatewayCommand",
    "BulkAddItemsToCartGatewayGroup",
    "CalculateOrgPackagePriceGatewayCommand",
    "CartItemLinkType",
    "ClickCountType",
    "CreateAccommodationDetailRequestGatewayCommand",
    "CreateAccommodationOfferRequestGatewayCommand",
    "CreateAccommodationPoolRequestGatewayCommand",
    "CreateAccommodationSimpleRequestGatewayCommand",
    "CreateAddServiceDetailRequestGatewayCommand",
    "CreateAddServiceOfferRequestGatewayCommand",
    "CreateAddServiceOfferRequestToServiceProviderGatewayCommand",
    "CreateAddServiceSimpleRequestGatewayCommand",
    "CreateClickCountGatewayCommand",
    "CreateFilterObject",
    "CreateFilterObjectDSApi",
    "CreateOfferRequestToServiceProviderGatewayCommand",
    "CreatePackageRequestGatewayCommand",
    "CreatePriceMatrixResultCommand",
    "CreateSearchObject",
    "CreateSearchObjectDSApi",
    "CreateTourVariantsSearchResultGatewayCommand",
    "DurationType",
    "EndUserConsents",
    "ExternalPersonInformationData",
    "FeratelGuestCardInputData",
    "FeratelGuestCardItem",
    "FilterAccommodation",
    "FilterAddServices",
    "FilterBehaviour",
    "FilterBrochure",
    "FilterEvent",
    "FilterInfrastructure",
    "FilterObject",
    "FilterPackage",
    "FilterTour",
    "GuestCardFilter",
    "GuestCardProcessMode",
    "GuestConsents",
    "GuestInfo",
    "GuestInfoCreateAccommodationDetailRequestGatewayCommand",
    "GuestInfoCreateAccommodationOfferRequestGatewayCommand",
    "GuestInfoCreateAccommodationPoolRequestGatewayCommand",
    "GuestInfoCreateAccommodationSimpleRequestGatewayCommand",
    "GuestInfoCreateAddServiceDetailRequestGatewayCommand",
    "GuestInfoCreateAddServiceOfferRequestGatewayCommand",
    "GuestInfoCreateAddServiceOfferRequestToServiceProviderGatewayCommand",
    "GuestInfoCreateAddServiceSimpleRequestGatewayCommand",
    "GuestInfoCreateOfferRequestToServiceProviderGatewayCommand",
    "GuestInfoCreatePackageRequestGatewayCommand",
    "ICheckoutQuestionAnswer",
    "LocationDistanceType",
    "LocationType",
    "MealType",
    "OccupancyData",
    "OrgPackageAssignmentsOccupancy",
    "PackageHeaderType",
    "PaymentProviderType",
    "PriceFilter",
    "QAQuestionValueType",
    "RatingType",
    "RequestFilterAdditionalServiceDetails",
    "RequestFilterDetails",
    "RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand",
    "RequestFilterDetailsCreateAccommodationPoolRequestGatewayCommand",
    "RequestParentType",
    "RequestPoolCommunicationType",
    "RequestPoolContactData",
    "SalutationSex",
    "SaveEndUserCommand",
    "SaveEndUserCommandUpdateShoppingCartGuestDataCommand",
    "SearchAccommodation",
    "SearchAddServices",
    "SearchData",
    "SearchEvent",
    "SearchGeneral",
    "SearchLine",
    "SearchObject",
    "SearchPackage",
    "SearchTour",
    "Section",
    "SectionChildrenAge",
    "ShoppingCartItemType",
    "ShoppingListAddAccommodationItemGatewayCommand",
    "ShoppingListAddAdditionalServiceItemGatewayCommand",
    "ShoppingListAddBrochureItemGatewayCommand",
    "ShoppingListAddPackageItemGatewayCommand",
    "ShoppingListAddTourItemGatewayCommand",
    "ShoppingListBulkAddItemsToShoppingListGatewayCommand",
    "SkiDataDeliveryModeType",
    "SkiDataInputData",
    "SkiDataPackageInputData",
    "SkiDataPackageItem",
    "SkiDataPackageItemTicketInputData",
    "SkiDataPackageItemType",
    "SkiDataProcessMode",
    "SkiDataTicketItem",
    "SwissPassData",
    "TransactionPaymentMethod",
    "UpdateAccommodationItemCommand",
    "UpdateAddServiceExternalData",
    "UpdateAdditionalServiceItemGatewayCommand",
    "UpdateBrochureItemCommand",
    "UpdateCheckoutQuestionCommand",
    "UpdateCheckoutQuestionGatewayCommand",
    "UpdateFilterObject",
    "UpdateSearchObject",
    "UpdateShoppingCartGuestDataCommand",
    "UpdateShoppingCartPaymentDataCommand",
    "UpdateSkiDataPackageData",
    "UpdateTourItemCommand",
    "ValidateSwissPassCommand",
    "VoucherData",
    "WaldhartSelection",
]

# import apis into sdk package
from feratel_client.api.accommodations_api import AccommodationsApi as AccommodationsApi
from feratel_client.api.add_services_api import AddServicesApi as AddServicesApi
from feratel_client.api.auth_api import AuthApi as AuthApi
from feratel_client.api.brochures_api import BrochuresApi as BrochuresApi
from feratel_client.api.click_count_api import ClickCountApi as ClickCountApi
from feratel_client.api.convert_api import ConvertApi as ConvertApi
from feratel_client.api.events_api import EventsApi as EventsApi
from feratel_client.api.filters_api import FiltersApi as FiltersApi
from feratel_client.api.infrastructures_api import InfrastructuresApi as InfrastructuresApi
from feratel_client.api.key_values_api import KeyValuesApi as KeyValuesApi
from feratel_client.api.packages_api import PackagesApi as PackagesApi
from feratel_client.api.requests_api import RequestsApi as RequestsApi
from feratel_client.api.searches_api import SearchesApi as SearchesApi
from feratel_client.api.shopping_cart_api import ShoppingCartApi as ShoppingCartApi
from feratel_client.api.shopping_list_api import ShoppingListApi as ShoppingListApi
from feratel_client.api.tours_api import ToursApi as ToursApi

# import ApiClient
from feratel_client.api_response import ApiResponse as ApiResponse
from feratel_client.api_client import ApiClient as ApiClient
from feratel_client.configuration import Configuration as Configuration
from feratel_client.exceptions import OpenApiException as OpenApiException
from feratel_client.exceptions import ApiTypeError as ApiTypeError
from feratel_client.exceptions import ApiValueError as ApiValueError
from feratel_client.exceptions import ApiKeyError as ApiKeyError
from feratel_client.exceptions import ApiAttributeError as ApiAttributeError
from feratel_client.exceptions import ApiException as ApiException

# import models into sdk package
from feratel_client.models.add_accommodation_item_gateway_command import AddAccommodationItemGatewayCommand as AddAccommodationItemGatewayCommand
from feratel_client.models.add_additional_service_item_gateway_command import AddAdditionalServiceItemGatewayCommand as AddAdditionalServiceItemGatewayCommand
from feratel_client.models.add_article_item_gateway_command import AddArticleItemGatewayCommand as AddArticleItemGatewayCommand
from feratel_client.models.add_brochure_item_gateway_command import AddBrochureItemGatewayCommand as AddBrochureItemGatewayCommand
from feratel_client.models.add_item_linked_data_gateway_command import AddItemLinkedDataGatewayCommand as AddItemLinkedDataGatewayCommand
from feratel_client.models.add_package_item_gateway_command import AddPackageItemGatewayCommand as AddPackageItemGatewayCommand
from feratel_client.models.add_package_section_item_child_ages_command import AddPackageSectionItemChildAgesCommand as AddPackageSectionItemChildAgesCommand
from feratel_client.models.add_package_section_item_command import AddPackageSectionItemCommand as AddPackageSectionItemCommand
from feratel_client.models.add_recommended_addon_item_gateway_command import AddRecommendedAddonItemGatewayCommand as AddRecommendedAddonItemGatewayCommand
from feratel_client.models.add_service_price_overrides import AddServicePriceOverrides as AddServicePriceOverrides
from feratel_client.models.add_tour_item_gateway_command import AddTourItemGatewayCommand as AddTourItemGatewayCommand
from feratel_client.models.additional_service_age_restriction import AdditionalServiceAgeRestriction as AdditionalServiceAgeRestriction
from feratel_client.models.arriving_guest import ArrivingGuest as ArrivingGuest
from feratel_client.models.axess_delivery_mode_type import AxessDeliveryModeType as AxessDeliveryModeType
from feratel_client.models.axess_process_mode import AxessProcessMode as AxessProcessMode
from feratel_client.models.axess_ticket_input_data import AxessTicketInputData as AxessTicketInputData
from feratel_client.models.axess_ticket_item import AxessTicketItem as AxessTicketItem
from feratel_client.models.bulk_add_items_to_cart_gateway_command import BulkAddItemsToCartGatewayCommand as BulkAddItemsToCartGatewayCommand
from feratel_client.models.bulk_add_items_to_cart_gateway_group import BulkAddItemsToCartGatewayGroup as BulkAddItemsToCartGatewayGroup
from feratel_client.models.calculate_org_package_price_gateway_command import CalculateOrgPackagePriceGatewayCommand as CalculateOrgPackagePriceGatewayCommand
from feratel_client.models.cart_item_link_type import CartItemLinkType as CartItemLinkType
from feratel_client.models.click_count_type import ClickCountType as ClickCountType
from feratel_client.models.create_accommodation_detail_request_gateway_command import CreateAccommodationDetailRequestGatewayCommand as CreateAccommodationDetailRequestGatewayCommand
from feratel_client.models.create_accommodation_offer_request_gateway_command import CreateAccommodationOfferRequestGatewayCommand as CreateAccommodationOfferRequestGatewayCommand
from feratel_client.models.create_accommodation_pool_request_gateway_command import CreateAccommodationPoolRequestGatewayCommand as CreateAccommodationPoolRequestGatewayCommand
from feratel_client.models.create_accommodation_simple_request_gateway_command import CreateAccommodationSimpleRequestGatewayCommand as CreateAccommodationSimpleRequestGatewayCommand
from feratel_client.models.create_add_service_detail_request_gateway_command import CreateAddServiceDetailRequestGatewayCommand as CreateAddServiceDetailRequestGatewayCommand
from feratel_client.models.create_add_service_offer_request_gateway_command import CreateAddServiceOfferRequestGatewayCommand as CreateAddServiceOfferRequestGatewayCommand
from feratel_client.models.create_add_service_offer_request_to_service_provider_gateway_command import CreateAddServiceOfferRequestToServiceProviderGatewayCommand as CreateAddServiceOfferRequestToServiceProviderGatewayCommand
from feratel_client.models.create_add_service_simple_request_gateway_command import CreateAddServiceSimpleRequestGatewayCommand as CreateAddServiceSimpleRequestGatewayCommand
from feratel_client.models.create_click_count_gateway_command import CreateClickCountGatewayCommand as CreateClickCountGatewayCommand
from feratel_client.models.create_filter_object import CreateFilterObject as CreateFilterObject
from feratel_client.models.create_filter_object_ds_api import CreateFilterObjectDSApi as CreateFilterObjectDSApi
from feratel_client.models.create_offer_request_to_service_provider_gateway_command import CreateOfferRequestToServiceProviderGatewayCommand as CreateOfferRequestToServiceProviderGatewayCommand
from feratel_client.models.create_package_request_gateway_command import CreatePackageRequestGatewayCommand as CreatePackageRequestGatewayCommand
from feratel_client.models.create_price_matrix_result_command import CreatePriceMatrixResultCommand as CreatePriceMatrixResultCommand
from feratel_client.models.create_search_object import CreateSearchObject as CreateSearchObject
from feratel_client.models.create_search_object_ds_api import CreateSearchObjectDSApi as CreateSearchObjectDSApi
from feratel_client.models.create_tour_variants_search_result_gateway_command import CreateTourVariantsSearchResultGatewayCommand as CreateTourVariantsSearchResultGatewayCommand
from feratel_client.models.duration_type import DurationType as DurationType
from feratel_client.models.end_user_consents import EndUserConsents as EndUserConsents
from feratel_client.models.external_person_information_data import ExternalPersonInformationData as ExternalPersonInformationData
from feratel_client.models.feratel_guest_card_input_data import FeratelGuestCardInputData as FeratelGuestCardInputData
from feratel_client.models.feratel_guest_card_item import FeratelGuestCardItem as FeratelGuestCardItem
from feratel_client.models.filter_accommodation import FilterAccommodation as FilterAccommodation
from feratel_client.models.filter_add_services import FilterAddServices as FilterAddServices
from feratel_client.models.filter_behaviour import FilterBehaviour as FilterBehaviour
from feratel_client.models.filter_brochure import FilterBrochure as FilterBrochure
from feratel_client.models.filter_event import FilterEvent as FilterEvent
from feratel_client.models.filter_infrastructure import FilterInfrastructure as FilterInfrastructure
from feratel_client.models.filter_object import FilterObject as FilterObject
from feratel_client.models.filter_package import FilterPackage as FilterPackage
from feratel_client.models.filter_tour import FilterTour as FilterTour
from feratel_client.models.guest_card_filter import GuestCardFilter as GuestCardFilter
from feratel_client.models.guest_card_process_mode import GuestCardProcessMode as GuestCardProcessMode
from feratel_client.models.guest_consents import GuestConsents as GuestConsents
from feratel_client.models.guest_info import GuestInfo as GuestInfo
from feratel_client.models.guest_info_create_accommodation_detail_request_gateway_command import GuestInfoCreateAccommodationDetailRequestGatewayCommand as GuestInfoCreateAccommodationDetailRequestGatewayCommand
from feratel_client.models.guest_info_create_accommodation_offer_request_gateway_command import GuestInfoCreateAccommodationOfferRequestGatewayCommand as GuestInfoCreateAccommodationOfferRequestGatewayCommand
from feratel_client.models.guest_info_create_accommodation_pool_request_gateway_command import GuestInfoCreateAccommodationPoolRequestGatewayCommand as GuestInfoCreateAccommodationPoolRequestGatewayCommand
from feratel_client.models.guest_info_create_accommodation_simple_request_gateway_command import GuestInfoCreateAccommodationSimpleRequestGatewayCommand as GuestInfoCreateAccommodationSimpleRequestGatewayCommand
from feratel_client.models.guest_info_create_add_service_detail_request_gateway_command import GuestInfoCreateAddServiceDetailRequestGatewayCommand as GuestInfoCreateAddServiceDetailRequestGatewayCommand
from feratel_client.models.guest_info_create_add_service_offer_request_gateway_command import GuestInfoCreateAddServiceOfferRequestGatewayCommand as GuestInfoCreateAddServiceOfferRequestGatewayCommand
from feratel_client.models.guest_info_create_add_service_offer_request_to_service_provider_gateway_command import GuestInfoCreateAddServiceOfferRequestToServiceProviderGatewayCommand as GuestInfoCreateAddServiceOfferRequestToServiceProviderGatewayCommand
from feratel_client.models.guest_info_create_add_service_simple_request_gateway_command import GuestInfoCreateAddServiceSimpleRequestGatewayCommand as GuestInfoCreateAddServiceSimpleRequestGatewayCommand
from feratel_client.models.guest_info_create_offer_request_to_service_provider_gateway_command import GuestInfoCreateOfferRequestToServiceProviderGatewayCommand as GuestInfoCreateOfferRequestToServiceProviderGatewayCommand
from feratel_client.models.guest_info_create_package_request_gateway_command import GuestInfoCreatePackageRequestGatewayCommand as GuestInfoCreatePackageRequestGatewayCommand
from feratel_client.models.i_checkout_question_answer import ICheckoutQuestionAnswer as ICheckoutQuestionAnswer
from feratel_client.models.location_distance_type import LocationDistanceType as LocationDistanceType
from feratel_client.models.location_type import LocationType as LocationType
from feratel_client.models.meal_type import MealType as MealType
from feratel_client.models.occupancy_data import OccupancyData as OccupancyData
from feratel_client.models.org_package_assignments_occupancy import OrgPackageAssignmentsOccupancy as OrgPackageAssignmentsOccupancy
from feratel_client.models.package_header_type import PackageHeaderType as PackageHeaderType
from feratel_client.models.payment_provider_type import PaymentProviderType as PaymentProviderType
from feratel_client.models.price_filter import PriceFilter as PriceFilter
from feratel_client.models.qa_question_value_type import QAQuestionValueType as QAQuestionValueType
from feratel_client.models.rating_type import RatingType as RatingType
from feratel_client.models.request_filter_additional_service_details import RequestFilterAdditionalServiceDetails as RequestFilterAdditionalServiceDetails
from feratel_client.models.request_filter_details import RequestFilterDetails as RequestFilterDetails
from feratel_client.models.request_filter_details_create_accommodation_offer_request_gateway_command import RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand as RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand
from feratel_client.models.request_filter_details_create_accommodation_pool_request_gateway_command import RequestFilterDetailsCreateAccommodationPoolRequestGatewayCommand as RequestFilterDetailsCreateAccommodationPoolRequestGatewayCommand
from feratel_client.models.request_parent_type import RequestParentType as RequestParentType
from feratel_client.models.request_pool_communication_type import RequestPoolCommunicationType as RequestPoolCommunicationType
from feratel_client.models.request_pool_contact_data import RequestPoolContactData as RequestPoolContactData
from feratel_client.models.salutation_sex import SalutationSex as SalutationSex
from feratel_client.models.save_end_user_command import SaveEndUserCommand as SaveEndUserCommand
from feratel_client.models.save_end_user_command_update_shopping_cart_guest_data_command import SaveEndUserCommandUpdateShoppingCartGuestDataCommand as SaveEndUserCommandUpdateShoppingCartGuestDataCommand
from feratel_client.models.search_accommodation import SearchAccommodation as SearchAccommodation
from feratel_client.models.search_add_services import SearchAddServices as SearchAddServices
from feratel_client.models.search_data import SearchData as SearchData
from feratel_client.models.search_event import SearchEvent as SearchEvent
from feratel_client.models.search_general import SearchGeneral as SearchGeneral
from feratel_client.models.search_line import SearchLine as SearchLine
from feratel_client.models.search_object import SearchObject as SearchObject
from feratel_client.models.search_package import SearchPackage as SearchPackage
from feratel_client.models.search_tour import SearchTour as SearchTour
from feratel_client.models.section import Section as Section
from feratel_client.models.section_children_age import SectionChildrenAge as SectionChildrenAge
from feratel_client.models.shopping_cart_item_type import ShoppingCartItemType as ShoppingCartItemType
from feratel_client.models.shopping_list_add_accommodation_item_gateway_command import ShoppingListAddAccommodationItemGatewayCommand as ShoppingListAddAccommodationItemGatewayCommand
from feratel_client.models.shopping_list_add_additional_service_item_gateway_command import ShoppingListAddAdditionalServiceItemGatewayCommand as ShoppingListAddAdditionalServiceItemGatewayCommand
from feratel_client.models.shopping_list_add_brochure_item_gateway_command import ShoppingListAddBrochureItemGatewayCommand as ShoppingListAddBrochureItemGatewayCommand
from feratel_client.models.shopping_list_add_package_item_gateway_command import ShoppingListAddPackageItemGatewayCommand as ShoppingListAddPackageItemGatewayCommand
from feratel_client.models.shopping_list_add_tour_item_gateway_command import ShoppingListAddTourItemGatewayCommand as ShoppingListAddTourItemGatewayCommand
from feratel_client.models.shopping_list_bulk_add_items_to_shopping_list_gateway_command import ShoppingListBulkAddItemsToShoppingListGatewayCommand as ShoppingListBulkAddItemsToShoppingListGatewayCommand
from feratel_client.models.ski_data_delivery_mode_type import SkiDataDeliveryModeType as SkiDataDeliveryModeType
from feratel_client.models.ski_data_input_data import SkiDataInputData as SkiDataInputData
from feratel_client.models.ski_data_package_input_data import SkiDataPackageInputData as SkiDataPackageInputData
from feratel_client.models.ski_data_package_item import SkiDataPackageItem as SkiDataPackageItem
from feratel_client.models.ski_data_package_item_ticket_input_data import SkiDataPackageItemTicketInputData as SkiDataPackageItemTicketInputData
from feratel_client.models.ski_data_package_item_type import SkiDataPackageItemType as SkiDataPackageItemType
from feratel_client.models.ski_data_process_mode import SkiDataProcessMode as SkiDataProcessMode
from feratel_client.models.ski_data_ticket_item import SkiDataTicketItem as SkiDataTicketItem
from feratel_client.models.swiss_pass_data import SwissPassData as SwissPassData
from feratel_client.models.transaction_payment_method import TransactionPaymentMethod as TransactionPaymentMethod
from feratel_client.models.update_accommodation_item_command import UpdateAccommodationItemCommand as UpdateAccommodationItemCommand
from feratel_client.models.update_add_service_external_data import UpdateAddServiceExternalData as UpdateAddServiceExternalData
from feratel_client.models.update_additional_service_item_gateway_command import UpdateAdditionalServiceItemGatewayCommand as UpdateAdditionalServiceItemGatewayCommand
from feratel_client.models.update_brochure_item_command import UpdateBrochureItemCommand as UpdateBrochureItemCommand
from feratel_client.models.update_checkout_question_command import UpdateCheckoutQuestionCommand as UpdateCheckoutQuestionCommand
from feratel_client.models.update_checkout_question_gateway_command import UpdateCheckoutQuestionGatewayCommand as UpdateCheckoutQuestionGatewayCommand
from feratel_client.models.update_filter_object import UpdateFilterObject as UpdateFilterObject
from feratel_client.models.update_search_object import UpdateSearchObject as UpdateSearchObject
from feratel_client.models.update_shopping_cart_guest_data_command import UpdateShoppingCartGuestDataCommand as UpdateShoppingCartGuestDataCommand
from feratel_client.models.update_shopping_cart_payment_data_command import UpdateShoppingCartPaymentDataCommand as UpdateShoppingCartPaymentDataCommand
from feratel_client.models.update_ski_data_package_data import UpdateSkiDataPackageData as UpdateSkiDataPackageData
from feratel_client.models.update_tour_item_command import UpdateTourItemCommand as UpdateTourItemCommand
from feratel_client.models.validate_swiss_pass_command import ValidateSwissPassCommand as ValidateSwissPassCommand
from feratel_client.models.voucher_data import VoucherData as VoucherData
from feratel_client.models.waldhart_selection import WaldhartSelection as WaldhartSelection

