# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from feratel_client.models.shopping_cart_item_type import ShoppingCartItemType
from typing import Optional, Set
from typing_extensions import Self

class AddTourItemGatewayCommand(BaseModel):
    """
    AddTourItemGatewayCommand
    """ # noqa: E501
    item_type: Optional[ShoppingCartItemType] = Field(default=None, alias="itemType")
    product_id: Optional[UUID] = Field(default=None, alias="productId")
    database_code: Optional[StrictStr] = Field(default=None, alias="databaseCode")
    units: Optional[StrictInt] = None
    group_number: Optional[StrictInt] = Field(default=None, alias="groupNumber")
    tour_id: Optional[UUID] = Field(default=None, alias="tourId")
    arrival_date: Optional[datetime] = Field(default=None, alias="arrivalDate")
    starting_time: Optional[StrictStr] = Field(default=None, alias="startingTime")
    duration_value: Optional[StrictInt] = Field(default=None, alias="durationValue")
    language: Optional[StrictStr] = None
    people: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["itemType", "productId", "databaseCode", "units", "groupNumber", "tourId", "arrivalDate", "startingTime", "durationValue", "language", "people"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddTourItemGatewayCommand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if database_code (nullable) is None
        # and model_fields_set contains the field
        if self.database_code is None and "database_code" in self.model_fields_set:
            _dict['databaseCode'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddTourItemGatewayCommand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "itemType": obj.get("itemType"),
            "productId": obj.get("productId"),
            "databaseCode": obj.get("databaseCode"),
            "units": obj.get("units"),
            "groupNumber": obj.get("groupNumber"),
            "tourId": obj.get("tourId"),
            "arrivalDate": obj.get("arrivalDate"),
            "startingTime": obj.get("startingTime"),
            "durationValue": obj.get("durationValue"),
            "language": obj.get("language"),
            "people": obj.get("people")
        })
        return _obj


