# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from feratel_client.models.axess_process_mode import AxessProcessMode
from feratel_client.models.axess_ticket_input_data import AxessTicketInputData
from feratel_client.models.external_person_information_data import ExternalPersonInformationData
from feratel_client.models.swiss_pass_data import SwissPassData
from typing import Optional, Set
from typing_extensions import Self

class AxessTicketItem(BaseModel):
    """
    AxessTicketItem
    """ # noqa: E501
    id: Optional[UUID] = None
    item_id: Optional[UUID] = Field(default=None, alias="itemId")
    mode: Optional[AxessProcessMode] = None
    person: Optional[ExternalPersonInformationData] = None
    axess_input_data: Optional[AxessTicketInputData] = Field(default=None, alias="axessInputData")
    swiss_pass_data: Optional[SwissPassData] = Field(default=None, alias="swissPassData")
    __properties: ClassVar[List[str]] = ["id", "itemId", "mode", "person", "axessInputData", "swissPassData"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AxessTicketItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of person
        if self.person:
            _dict['person'] = self.person.to_dict()
        # override the default output from pydantic by calling `to_dict()` of axess_input_data
        if self.axess_input_data:
            _dict['axessInputData'] = self.axess_input_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of swiss_pass_data
        if self.swiss_pass_data:
            _dict['swissPassData'] = self.swiss_pass_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AxessTicketItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "itemId": obj.get("itemId"),
            "mode": obj.get("mode"),
            "person": ExternalPersonInformationData.from_dict(obj["person"]) if obj.get("person") is not None else None,
            "axessInputData": AxessTicketInputData.from_dict(obj["axessInputData"]) if obj.get("axessInputData") is not None else None,
            "swissPassData": SwissPassData.from_dict(obj["swissPassData"]) if obj.get("swissPassData") is not None else None
        })
        return _obj


