# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from feratel_client.models.guest_info_create_accommodation_detail_request_gateway_command import GuestInfoCreateAccommodationDetailRequestGatewayCommand
from feratel_client.models.meal_type import MealType
from feratel_client.models.occupancy_data import OccupancyData
from feratel_client.models.search_data import SearchData
from typing import Optional, Set
from typing_extensions import Self

class CreateAccommodationDetailRequestGatewayCommand(BaseModel):
    """
    CreateAccommodationDetailRequestGatewayCommand
    """ # noqa: E501
    guest: Optional[GuestInfoCreateAccommodationDetailRequestGatewayCommand] = None
    message_from_guest: Optional[StrictStr] = Field(default=None, alias="messageFromGuest")
    service_provider_id: Optional[UUID] = Field(default=None, alias="serviceProviderId")
    organisation_code: Optional[StrictStr] = Field(default=None, alias="organisationCode")
    product_ids: Optional[List[UUID]] = Field(default=None, alias="productIds")
    search_data: Optional[SearchData] = Field(default=None, alias="searchData")
    occupancy_data: Optional[List[OccupancyData]] = Field(default=None, alias="occupancyData")
    meal_type: Optional[MealType] = Field(default=None, alias="mealType")
    __properties: ClassVar[List[str]] = ["guest", "messageFromGuest", "serviceProviderId", "organisationCode", "productIds", "searchData", "occupancyData", "mealType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAccommodationDetailRequestGatewayCommand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of guest
        if self.guest:
            _dict['guest'] = self.guest.to_dict()
        # override the default output from pydantic by calling `to_dict()` of search_data
        if self.search_data:
            _dict['searchData'] = self.search_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in occupancy_data (list)
        _items = []
        if self.occupancy_data:
            for _item_occupancy_data in self.occupancy_data:
                if _item_occupancy_data:
                    _items.append(_item_occupancy_data.to_dict())
            _dict['occupancyData'] = _items
        # set to None if message_from_guest (nullable) is None
        # and model_fields_set contains the field
        if self.message_from_guest is None and "message_from_guest" in self.model_fields_set:
            _dict['messageFromGuest'] = None

        # set to None if organisation_code (nullable) is None
        # and model_fields_set contains the field
        if self.organisation_code is None and "organisation_code" in self.model_fields_set:
            _dict['organisationCode'] = None

        # set to None if product_ids (nullable) is None
        # and model_fields_set contains the field
        if self.product_ids is None and "product_ids" in self.model_fields_set:
            _dict['productIds'] = None

        # set to None if occupancy_data (nullable) is None
        # and model_fields_set contains the field
        if self.occupancy_data is None and "occupancy_data" in self.model_fields_set:
            _dict['occupancyData'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAccommodationDetailRequestGatewayCommand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "guest": GuestInfoCreateAccommodationDetailRequestGatewayCommand.from_dict(obj["guest"]) if obj.get("guest") is not None else None,
            "messageFromGuest": obj.get("messageFromGuest"),
            "serviceProviderId": obj.get("serviceProviderId"),
            "organisationCode": obj.get("organisationCode"),
            "productIds": obj.get("productIds"),
            "searchData": SearchData.from_dict(obj["searchData"]) if obj.get("searchData") is not None else None,
            "occupancyData": [OccupancyData.from_dict(_item) for _item in obj["occupancyData"]] if obj.get("occupancyData") is not None else None,
            "mealType": obj.get("mealType")
        })
        return _obj


