# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from feratel_client.models.guest_info_create_accommodation_offer_request_gateway_command import GuestInfoCreateAccommodationOfferRequestGatewayCommand
from feratel_client.models.occupancy_data import OccupancyData
from feratel_client.models.request_filter_details_create_accommodation_offer_request_gateway_command import RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand
from feratel_client.models.search_data import SearchData
from typing import Optional, Set
from typing_extensions import Self

class CreateAccommodationOfferRequestGatewayCommand(BaseModel):
    """
    CreateAccommodationOfferRequestGatewayCommand
    """ # noqa: E501
    search_data: Optional[SearchData] = Field(default=None, alias="searchData")
    guest: Optional[GuestInfoCreateAccommodationOfferRequestGatewayCommand] = None
    occupancy_data: Optional[List[OccupancyData]] = Field(default=None, alias="occupancyData")
    filter_details: Optional[RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand] = Field(default=None, alias="filterDetails")
    message: Optional[StrictStr] = None
    currency_code: Optional[StrictStr] = Field(default=None, alias="currencyCode")
    __properties: ClassVar[List[str]] = ["searchData", "guest", "occupancyData", "filterDetails", "message", "currencyCode"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAccommodationOfferRequestGatewayCommand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of search_data
        if self.search_data:
            _dict['searchData'] = self.search_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of guest
        if self.guest:
            _dict['guest'] = self.guest.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in occupancy_data (list)
        _items = []
        if self.occupancy_data:
            for _item_occupancy_data in self.occupancy_data:
                if _item_occupancy_data:
                    _items.append(_item_occupancy_data.to_dict())
            _dict['occupancyData'] = _items
        # override the default output from pydantic by calling `to_dict()` of filter_details
        if self.filter_details:
            _dict['filterDetails'] = self.filter_details.to_dict()
        # set to None if occupancy_data (nullable) is None
        # and model_fields_set contains the field
        if self.occupancy_data is None and "occupancy_data" in self.model_fields_set:
            _dict['occupancyData'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if currency_code (nullable) is None
        # and model_fields_set contains the field
        if self.currency_code is None and "currency_code" in self.model_fields_set:
            _dict['currencyCode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAccommodationOfferRequestGatewayCommand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "searchData": SearchData.from_dict(obj["searchData"]) if obj.get("searchData") is not None else None,
            "guest": GuestInfoCreateAccommodationOfferRequestGatewayCommand.from_dict(obj["guest"]) if obj.get("guest") is not None else None,
            "occupancyData": [OccupancyData.from_dict(_item) for _item in obj["occupancyData"]] if obj.get("occupancyData") is not None else None,
            "filterDetails": RequestFilterDetailsCreateAccommodationOfferRequestGatewayCommand.from_dict(obj["filterDetails"]) if obj.get("filterDetails") is not None else None,
            "message": obj.get("message"),
            "currencyCode": obj.get("currencyCode")
        })
        return _obj


