# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from feratel_client.models.filter_accommodation import FilterAccommodation
from feratel_client.models.filter_add_services import FilterAddServices
from feratel_client.models.filter_brochure import FilterBrochure
from feratel_client.models.filter_event import FilterEvent
from feratel_client.models.filter_infrastructure import FilterInfrastructure
from feratel_client.models.filter_package import FilterPackage
from feratel_client.models.filter_tour import FilterTour
from typing import Optional, Set
from typing_extensions import Self

class CreateFilterObjectDSApi(BaseModel):
    """
    CreateFilterObjectDSApi
    """ # noqa: E501
    filter_general: Optional[Dict[str, Any]] = Field(default=None, alias="filterGeneral")
    filter_add_services: Optional[FilterAddServices] = Field(default=None, alias="filterAddServices")
    filter_accommodation: Optional[FilterAccommodation] = Field(default=None, alias="filterAccommodation")
    filter_event: Optional[FilterEvent] = Field(default=None, alias="filterEvent")
    filter_infrastructure: Optional[FilterInfrastructure] = Field(default=None, alias="filterInfrastructure")
    filter_brochure: Optional[FilterBrochure] = Field(default=None, alias="filterBrochure")
    filter_package: Optional[FilterPackage] = Field(default=None, alias="filterPackage")
    filter_tour: Optional[FilterTour] = Field(default=None, alias="filterTour")
    __properties: ClassVar[List[str]] = ["filterGeneral", "filterAddServices", "filterAccommodation", "filterEvent", "filterInfrastructure", "filterBrochure", "filterPackage", "filterTour"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateFilterObjectDSApi from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of filter_add_services
        if self.filter_add_services:
            _dict['filterAddServices'] = self.filter_add_services.to_dict()
        # override the default output from pydantic by calling `to_dict()` of filter_accommodation
        if self.filter_accommodation:
            _dict['filterAccommodation'] = self.filter_accommodation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of filter_event
        if self.filter_event:
            _dict['filterEvent'] = self.filter_event.to_dict()
        # override the default output from pydantic by calling `to_dict()` of filter_infrastructure
        if self.filter_infrastructure:
            _dict['filterInfrastructure'] = self.filter_infrastructure.to_dict()
        # override the default output from pydantic by calling `to_dict()` of filter_brochure
        if self.filter_brochure:
            _dict['filterBrochure'] = self.filter_brochure.to_dict()
        # override the default output from pydantic by calling `to_dict()` of filter_package
        if self.filter_package:
            _dict['filterPackage'] = self.filter_package.to_dict()
        # override the default output from pydantic by calling `to_dict()` of filter_tour
        if self.filter_tour:
            _dict['filterTour'] = self.filter_tour.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateFilterObjectDSApi from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "filterGeneral": obj.get("filterGeneral"),
            "filterAddServices": FilterAddServices.from_dict(obj["filterAddServices"]) if obj.get("filterAddServices") is not None else None,
            "filterAccommodation": FilterAccommodation.from_dict(obj["filterAccommodation"]) if obj.get("filterAccommodation") is not None else None,
            "filterEvent": FilterEvent.from_dict(obj["filterEvent"]) if obj.get("filterEvent") is not None else None,
            "filterInfrastructure": FilterInfrastructure.from_dict(obj["filterInfrastructure"]) if obj.get("filterInfrastructure") is not None else None,
            "filterBrochure": FilterBrochure.from_dict(obj["filterBrochure"]) if obj.get("filterBrochure") is not None else None,
            "filterPackage": FilterPackage.from_dict(obj["filterPackage"]) if obj.get("filterPackage") is not None else None,
            "filterTour": FilterTour.from_dict(obj["filterTour"]) if obj.get("filterTour") is not None else None
        })
        return _obj


