# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from feratel_client.models.external_person_information_data import ExternalPersonInformationData
from feratel_client.models.feratel_guest_card_input_data import FeratelGuestCardInputData
from feratel_client.models.guest_card_process_mode import GuestCardProcessMode
from typing import Optional, Set
from typing_extensions import Self

class FeratelGuestCardItem(BaseModel):
    """
    FeratelGuestCardItem
    """ # noqa: E501
    item_id: Optional[UUID] = Field(default=None, alias="itemId")
    card_process_mode: Optional[GuestCardProcessMode] = Field(default=None, alias="cardProcessMode")
    card_input_data: Optional[FeratelGuestCardInputData] = Field(default=None, alias="cardInputData")
    person: Optional[ExternalPersonInformationData] = None
    __properties: ClassVar[List[str]] = ["itemId", "cardProcessMode", "cardInputData", "person"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeratelGuestCardItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of card_input_data
        if self.card_input_data:
            _dict['cardInputData'] = self.card_input_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of person
        if self.person:
            _dict['person'] = self.person.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeratelGuestCardItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "itemId": obj.get("itemId"),
            "cardProcessMode": obj.get("cardProcessMode"),
            "cardInputData": FeratelGuestCardInputData.from_dict(obj["cardInputData"]) if obj.get("cardInputData") is not None else None,
            "person": ExternalPersonInformationData.from_dict(obj["person"]) if obj.get("person") is not None else None
        })
        return _obj


