# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from feratel_client.models.filter_behaviour import FilterBehaviour
from feratel_client.models.guest_card_filter import GuestCardFilter
from typing import Optional, Set
from typing_extensions import Self

class FilterInfrastructure(BaseModel):
    """
    FilterInfrastructure
    """ # noqa: E501
    opening_times: Optional[List[StrictInt]] = Field(default=None, alias="openingTimes")
    infrastructure_types: Optional[List[UUID]] = Field(default=None, alias="infrastructureTypes")
    locations: Optional[List[UUID]] = None
    holiday_themes: Optional[List[UUID]] = Field(default=None, alias="holidayThemes")
    name: Optional[StrictStr] = None
    topics: Optional[List[UUID]] = None
    topics_behaviour: Optional[FilterBehaviour] = Field(default=None, alias="topicsBehaviour")
    guest_cards: Optional[List[GuestCardFilter]] = Field(default=None, alias="guestCards")
    classifications: Optional[List[UUID]] = None
    top_classifications: Optional[List[UUID]] = Field(default=None, alias="topClassifications")
    top_classifications_behaviour: Optional[FilterBehaviour] = Field(default=None, alias="topClassificationsBehaviour")
    __properties: ClassVar[List[str]] = ["openingTimes", "infrastructureTypes", "locations", "holidayThemes", "name", "topics", "topicsBehaviour", "guestCards", "classifications", "topClassifications", "topClassificationsBehaviour"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FilterInfrastructure from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in guest_cards (list)
        _items = []
        if self.guest_cards:
            for _item_guest_cards in self.guest_cards:
                if _item_guest_cards:
                    _items.append(_item_guest_cards.to_dict())
            _dict['guestCards'] = _items
        # set to None if opening_times (nullable) is None
        # and model_fields_set contains the field
        if self.opening_times is None and "opening_times" in self.model_fields_set:
            _dict['openingTimes'] = None

        # set to None if infrastructure_types (nullable) is None
        # and model_fields_set contains the field
        if self.infrastructure_types is None and "infrastructure_types" in self.model_fields_set:
            _dict['infrastructureTypes'] = None

        # set to None if locations (nullable) is None
        # and model_fields_set contains the field
        if self.locations is None and "locations" in self.model_fields_set:
            _dict['locations'] = None

        # set to None if holiday_themes (nullable) is None
        # and model_fields_set contains the field
        if self.holiday_themes is None and "holiday_themes" in self.model_fields_set:
            _dict['holidayThemes'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if topics (nullable) is None
        # and model_fields_set contains the field
        if self.topics is None and "topics" in self.model_fields_set:
            _dict['topics'] = None

        # set to None if guest_cards (nullable) is None
        # and model_fields_set contains the field
        if self.guest_cards is None and "guest_cards" in self.model_fields_set:
            _dict['guestCards'] = None

        # set to None if classifications (nullable) is None
        # and model_fields_set contains the field
        if self.classifications is None and "classifications" in self.model_fields_set:
            _dict['classifications'] = None

        # set to None if top_classifications (nullable) is None
        # and model_fields_set contains the field
        if self.top_classifications is None and "top_classifications" in self.model_fields_set:
            _dict['topClassifications'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FilterInfrastructure from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "openingTimes": obj.get("openingTimes"),
            "infrastructureTypes": obj.get("infrastructureTypes"),
            "locations": obj.get("locations"),
            "holidayThemes": obj.get("holidayThemes"),
            "name": obj.get("name"),
            "topics": obj.get("topics"),
            "topicsBehaviour": obj.get("topicsBehaviour"),
            "guestCards": [GuestCardFilter.from_dict(_item) for _item in obj["guestCards"]] if obj.get("guestCards") is not None else None,
            "classifications": obj.get("classifications"),
            "topClassifications": obj.get("topClassifications"),
            "topClassificationsBehaviour": obj.get("topClassificationsBehaviour")
        })
        return _obj


