# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from feratel_client.models.filter_behaviour import FilterBehaviour
from feratel_client.models.guest_card_filter import GuestCardFilter
from typing import Optional, Set
from typing_extensions import Self

class FilterAddServices(BaseModel):
    """
    FilterAddServices
    """ # noqa: E501
    types: Optional[List[UUID]] = None
    holiday_themes: Optional[List[UUID]] = Field(default=None, alias="holidayThemes")
    locations: Optional[List[UUID]] = None
    guest_cards: Optional[List[GuestCardFilter]] = Field(default=None, alias="guestCards")
    name: Optional[StrictStr] = None
    service_classifications: Optional[List[UUID]] = Field(default=None, alias="serviceClassifications")
    top_service_classifications: Optional[List[UUID]] = Field(default=None, alias="topServiceClassifications")
    top_service_classifications_behaviour: Optional[FilterBehaviour] = Field(default=None, alias="topServiceClassificationsBehaviour")
    __properties: ClassVar[List[str]] = ["types", "holidayThemes", "locations", "guestCards", "name", "serviceClassifications", "topServiceClassifications", "topServiceClassificationsBehaviour"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FilterAddServices from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in guest_cards (list)
        _items = []
        if self.guest_cards:
            for _item_guest_cards in self.guest_cards:
                if _item_guest_cards:
                    _items.append(_item_guest_cards.to_dict())
            _dict['guestCards'] = _items
        # set to None if types (nullable) is None
        # and model_fields_set contains the field
        if self.types is None and "types" in self.model_fields_set:
            _dict['types'] = None

        # set to None if holiday_themes (nullable) is None
        # and model_fields_set contains the field
        if self.holiday_themes is None and "holiday_themes" in self.model_fields_set:
            _dict['holidayThemes'] = None

        # set to None if locations (nullable) is None
        # and model_fields_set contains the field
        if self.locations is None and "locations" in self.model_fields_set:
            _dict['locations'] = None

        # set to None if guest_cards (nullable) is None
        # and model_fields_set contains the field
        if self.guest_cards is None and "guest_cards" in self.model_fields_set:
            _dict['guestCards'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if service_classifications (nullable) is None
        # and model_fields_set contains the field
        if self.service_classifications is None and "service_classifications" in self.model_fields_set:
            _dict['serviceClassifications'] = None

        # set to None if top_service_classifications (nullable) is None
        # and model_fields_set contains the field
        if self.top_service_classifications is None and "top_service_classifications" in self.model_fields_set:
            _dict['topServiceClassifications'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FilterAddServices from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "types": obj.get("types"),
            "holidayThemes": obj.get("holidayThemes"),
            "locations": obj.get("locations"),
            "guestCards": [GuestCardFilter.from_dict(_item) for _item in obj["guestCards"]] if obj.get("guestCards") is not None else None,
            "name": obj.get("name"),
            "serviceClassifications": obj.get("serviceClassifications"),
            "topServiceClassifications": obj.get("topServiceClassifications"),
            "topServiceClassificationsBehaviour": obj.get("topServiceClassificationsBehaviour")
        })
        return _obj


