# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from feratel_client.models.filter_behaviour import FilterBehaviour
from typing import Optional, Set
from typing_extensions import Self

class FilterTour(BaseModel):
    """
    FilterTour
    """ # noqa: E501
    languages: Optional[List[UUID]] = None
    categories: Optional[List[UUID]] = None
    holiday_themes: Optional[List[UUID]] = Field(default=None, alias="holidayThemes")
    name: Optional[StrictStr] = None
    top_tour: Optional[StrictBool] = Field(default=None, alias="topTour")
    classifications: Optional[List[UUID]] = None
    top_classifications: Optional[List[UUID]] = Field(default=None, alias="topClassifications")
    top_classifications_behaviour: Optional[FilterBehaviour] = Field(default=None, alias="topClassificationsBehaviour")
    __properties: ClassVar[List[str]] = ["languages", "categories", "holidayThemes", "name", "topTour", "classifications", "topClassifications", "topClassificationsBehaviour"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FilterTour from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if languages (nullable) is None
        # and model_fields_set contains the field
        if self.languages is None and "languages" in self.model_fields_set:
            _dict['languages'] = None

        # set to None if categories (nullable) is None
        # and model_fields_set contains the field
        if self.categories is None and "categories" in self.model_fields_set:
            _dict['categories'] = None

        # set to None if holiday_themes (nullable) is None
        # and model_fields_set contains the field
        if self.holiday_themes is None and "holiday_themes" in self.model_fields_set:
            _dict['holidayThemes'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if classifications (nullable) is None
        # and model_fields_set contains the field
        if self.classifications is None and "classifications" in self.model_fields_set:
            _dict['classifications'] = None

        # set to None if top_classifications (nullable) is None
        # and model_fields_set contains the field
        if self.top_classifications is None and "top_classifications" in self.model_fields_set:
            _dict['topClassifications'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FilterTour from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "languages": obj.get("languages"),
            "categories": obj.get("categories"),
            "holidayThemes": obj.get("holidayThemes"),
            "name": obj.get("name"),
            "topTour": obj.get("topTour"),
            "classifications": obj.get("classifications"),
            "topClassifications": obj.get("topClassifications"),
            "topClassificationsBehaviour": obj.get("topClassificationsBehaviour")
        })
        return _obj


