# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RatingType(int, Enum):
    """
    RatingType
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_1 = 1
    NUMBER_2 = 2
    NUMBER_5 = 5
    NUMBER_12 = 12
    NUMBER_32 = 32
    NUMBER_41 = 41
    NUMBER_51 = 51
    NUMBER_52 = 52
    NUMBER_MINUS_102 = -102
    NUMBER_MINUS_41 = -41
    NUMBER_MINUS_32 = -32
    NUMBER_MINUS_5 = -5
    NUMBER_MINUS_2 = -2
    NUMBER_MINUS_1 = -1

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RatingType from a JSON string"""
        return cls(json.loads(json_str))


