# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from feratel_client.models.meal_type import MealType
from typing import Optional, Set
from typing_extensions import Self

class RequestFilterDetailsCreateAccommodationPoolRequestGatewayCommand(BaseModel):
    """
    RequestFilterDetailsCreateAccommodationPoolRequestGatewayCommand
    """ # noqa: E501
    accommodation_name: Optional[StrictStr] = Field(default=None, alias="accommodationName")
    location_ids: Optional[List[UUID]] = Field(default=None, alias="locationIds")
    category_ids: Optional[List[UUID]] = Field(default=None, alias="categoryIds")
    star_ids: Optional[List[UUID]] = Field(default=None, alias="starIds")
    classification_ids: Optional[List[UUID]] = Field(default=None, alias="classificationIds")
    service_classification_ids: Optional[List[UUID]] = Field(default=None, alias="serviceClassificationIds")
    marketing_groups: Optional[List[UUID]] = Field(default=None, alias="marketingGroups")
    hotel_chains: Optional[List[UUID]] = Field(default=None, alias="hotelChains")
    holiday_themes: Optional[List[UUID]] = Field(default=None, alias="holidayThemes")
    features: Optional[List[UUID]] = None
    service_features: Optional[List[UUID]] = Field(default=None, alias="serviceFeatures")
    meal_type: Optional[MealType] = Field(default=None, alias="mealType")
    price_to: Optional[StrictInt] = Field(default=None, alias="priceTo")
    __properties: ClassVar[List[str]] = ["accommodationName", "locationIds", "categoryIds", "starIds", "classificationIds", "serviceClassificationIds", "marketingGroups", "hotelChains", "holidayThemes", "features", "serviceFeatures", "mealType", "priceTo"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RequestFilterDetailsCreateAccommodationPoolRequestGatewayCommand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if accommodation_name (nullable) is None
        # and model_fields_set contains the field
        if self.accommodation_name is None and "accommodation_name" in self.model_fields_set:
            _dict['accommodationName'] = None

        # set to None if location_ids (nullable) is None
        # and model_fields_set contains the field
        if self.location_ids is None and "location_ids" in self.model_fields_set:
            _dict['locationIds'] = None

        # set to None if category_ids (nullable) is None
        # and model_fields_set contains the field
        if self.category_ids is None and "category_ids" in self.model_fields_set:
            _dict['categoryIds'] = None

        # set to None if star_ids (nullable) is None
        # and model_fields_set contains the field
        if self.star_ids is None and "star_ids" in self.model_fields_set:
            _dict['starIds'] = None

        # set to None if classification_ids (nullable) is None
        # and model_fields_set contains the field
        if self.classification_ids is None and "classification_ids" in self.model_fields_set:
            _dict['classificationIds'] = None

        # set to None if service_classification_ids (nullable) is None
        # and model_fields_set contains the field
        if self.service_classification_ids is None and "service_classification_ids" in self.model_fields_set:
            _dict['serviceClassificationIds'] = None

        # set to None if marketing_groups (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_groups is None and "marketing_groups" in self.model_fields_set:
            _dict['marketingGroups'] = None

        # set to None if hotel_chains (nullable) is None
        # and model_fields_set contains the field
        if self.hotel_chains is None and "hotel_chains" in self.model_fields_set:
            _dict['hotelChains'] = None

        # set to None if holiday_themes (nullable) is None
        # and model_fields_set contains the field
        if self.holiday_themes is None and "holiday_themes" in self.model_fields_set:
            _dict['holidayThemes'] = None

        # set to None if features (nullable) is None
        # and model_fields_set contains the field
        if self.features is None and "features" in self.model_fields_set:
            _dict['features'] = None

        # set to None if service_features (nullable) is None
        # and model_fields_set contains the field
        if self.service_features is None and "service_features" in self.model_fields_set:
            _dict['serviceFeatures'] = None

        # set to None if price_to (nullable) is None
        # and model_fields_set contains the field
        if self.price_to is None and "price_to" in self.model_fields_set:
            _dict['priceTo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RequestFilterDetailsCreateAccommodationPoolRequestGatewayCommand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accommodationName": obj.get("accommodationName"),
            "locationIds": obj.get("locationIds"),
            "categoryIds": obj.get("categoryIds"),
            "starIds": obj.get("starIds"),
            "classificationIds": obj.get("classificationIds"),
            "serviceClassificationIds": obj.get("serviceClassificationIds"),
            "marketingGroups": obj.get("marketingGroups"),
            "hotelChains": obj.get("hotelChains"),
            "holidayThemes": obj.get("holidayThemes"),
            "features": obj.get("features"),
            "serviceFeatures": obj.get("serviceFeatures"),
            "mealType": obj.get("mealType"),
            "priceTo": obj.get("priceTo")
        })
        return _obj


