# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SalutationSex(int, Enum):
    """
    SalutationSex
    """

    """
    allowed enum values
    """
    NUMBER_100 = 100
    NUMBER_102 = 102
    NUMBER_103 = 103
    NUMBER_105 = 105
    NUMBER_109 = 109
    NUMBER_111 = 111
    NUMBER_117 = 117

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SalutationSex from a JSON string"""
        return cls(json.loads(json_str))


