# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from feratel_client.models.end_user_consents import EndUserConsents
from typing import Optional, Set
from typing_extensions import Self

class SaveEndUserCommand(BaseModel):
    """
    SaveEndUserCommand
    """ # noqa: E501
    database_code: Optional[StrictStr] = Field(default=None, alias="databaseCode")
    salutation_id: Optional[UUID] = Field(default=None, alias="salutationId")
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName")
    company: Optional[StrictStr] = None
    city: Optional[StrictStr] = None
    zip_code: Optional[StrictStr] = Field(default=None, alias="zipCode")
    email: Optional[StrictStr] = None
    address1: Optional[StrictStr] = None
    address2: Optional[StrictStr] = None
    country: Optional[StrictStr] = None
    mobile: Optional[StrictStr] = None
    phone: Optional[StrictStr] = None
    fax: Optional[StrictStr] = None
    reusable: Optional[StrictInt] = None
    currency_code: Optional[StrictStr] = Field(default=None, alias="currencyCode")
    language: Optional[StrictStr] = None
    salutation: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    uid_number: Optional[StrictStr] = Field(default=None, alias="uidNumber")
    owner: Optional[StrictStr] = None
    marketing_codes: Optional[StrictStr] = Field(default=None, alias="marketingCodes")
    consents: Optional[EndUserConsents] = None
    __properties: ClassVar[List[str]] = ["databaseCode", "salutationId", "firstName", "lastName", "company", "city", "zipCode", "email", "address1", "address2", "country", "mobile", "phone", "fax", "reusable", "currencyCode", "language", "salutation", "title", "uidNumber", "owner", "marketingCodes", "consents"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SaveEndUserCommand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of consents
        if self.consents:
            _dict['consents'] = self.consents.to_dict()
        # set to None if database_code (nullable) is None
        # and model_fields_set contains the field
        if self.database_code is None and "database_code" in self.model_fields_set:
            _dict['databaseCode'] = None

        # set to None if first_name (nullable) is None
        # and model_fields_set contains the field
        if self.first_name is None and "first_name" in self.model_fields_set:
            _dict['firstName'] = None

        # set to None if last_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_name is None and "last_name" in self.model_fields_set:
            _dict['lastName'] = None

        # set to None if company (nullable) is None
        # and model_fields_set contains the field
        if self.company is None and "company" in self.model_fields_set:
            _dict['company'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if zip_code (nullable) is None
        # and model_fields_set contains the field
        if self.zip_code is None and "zip_code" in self.model_fields_set:
            _dict['zipCode'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if address1 (nullable) is None
        # and model_fields_set contains the field
        if self.address1 is None and "address1" in self.model_fields_set:
            _dict['address1'] = None

        # set to None if address2 (nullable) is None
        # and model_fields_set contains the field
        if self.address2 is None and "address2" in self.model_fields_set:
            _dict['address2'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if mobile (nullable) is None
        # and model_fields_set contains the field
        if self.mobile is None and "mobile" in self.model_fields_set:
            _dict['mobile'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        # set to None if fax (nullable) is None
        # and model_fields_set contains the field
        if self.fax is None and "fax" in self.model_fields_set:
            _dict['fax'] = None

        # set to None if currency_code (nullable) is None
        # and model_fields_set contains the field
        if self.currency_code is None and "currency_code" in self.model_fields_set:
            _dict['currencyCode'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if salutation (nullable) is None
        # and model_fields_set contains the field
        if self.salutation is None and "salutation" in self.model_fields_set:
            _dict['salutation'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if uid_number (nullable) is None
        # and model_fields_set contains the field
        if self.uid_number is None and "uid_number" in self.model_fields_set:
            _dict['uidNumber'] = None

        # set to None if owner (nullable) is None
        # and model_fields_set contains the field
        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        # set to None if marketing_codes (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_codes is None and "marketing_codes" in self.model_fields_set:
            _dict['marketingCodes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SaveEndUserCommand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "databaseCode": obj.get("databaseCode"),
            "salutationId": obj.get("salutationId"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "company": obj.get("company"),
            "city": obj.get("city"),
            "zipCode": obj.get("zipCode"),
            "email": obj.get("email"),
            "address1": obj.get("address1"),
            "address2": obj.get("address2"),
            "country": obj.get("country"),
            "mobile": obj.get("mobile"),
            "phone": obj.get("phone"),
            "fax": obj.get("fax"),
            "reusable": obj.get("reusable"),
            "currencyCode": obj.get("currencyCode"),
            "language": obj.get("language"),
            "salutation": obj.get("salutation"),
            "title": obj.get("title"),
            "uidNumber": obj.get("uidNumber"),
            "owner": obj.get("owner"),
            "marketingCodes": obj.get("marketingCodes"),
            "consents": EndUserConsents.from_dict(obj["consents"]) if obj.get("consents") is not None else None
        })
        return _obj


