# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from feratel_client.models.search_accommodation import SearchAccommodation
from feratel_client.models.search_add_services import SearchAddServices
from feratel_client.models.search_general import SearchGeneral
from feratel_client.models.search_package import SearchPackage
from typing import Optional, Set
from typing_extensions import Self

class SearchObject(BaseModel):
    """
    SearchObject
    """ # noqa: E501
    id: Optional[UUID] = None
    search_general: Optional[SearchGeneral] = Field(default=None, alias="searchGeneral")
    search_accommodation: Optional[SearchAccommodation] = Field(default=None, alias="searchAccommodation")
    search_add_service: Optional[SearchAddServices] = Field(default=None, alias="searchAddService")
    search_package: Optional[SearchPackage] = Field(default=None, alias="searchPackage")
    __properties: ClassVar[List[str]] = ["id", "searchGeneral", "searchAccommodation", "searchAddService", "searchPackage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of search_general
        if self.search_general:
            _dict['searchGeneral'] = self.search_general.to_dict()
        # override the default output from pydantic by calling `to_dict()` of search_accommodation
        if self.search_accommodation:
            _dict['searchAccommodation'] = self.search_accommodation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of search_add_service
        if self.search_add_service:
            _dict['searchAddService'] = self.search_add_service.to_dict()
        # override the default output from pydantic by calling `to_dict()` of search_package
        if self.search_package:
            _dict['searchPackage'] = self.search_package.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "searchGeneral": SearchGeneral.from_dict(obj["searchGeneral"]) if obj.get("searchGeneral") is not None else None,
            "searchAccommodation": SearchAccommodation.from_dict(obj["searchAccommodation"]) if obj.get("searchAccommodation") is not None else None,
            "searchAddService": SearchAddServices.from_dict(obj["searchAddService"]) if obj.get("searchAddService") is not None else None,
            "searchPackage": SearchPackage.from_dict(obj["searchPackage"]) if obj.get("searchPackage") is not None else None
        })
        return _obj


