# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from feratel_client.models.shopping_list_add_accommodation_item_gateway_command import ShoppingListAddAccommodationItemGatewayCommand
from feratel_client.models.shopping_list_add_additional_service_item_gateway_command import ShoppingListAddAdditionalServiceItemGatewayCommand
from feratel_client.models.shopping_list_add_brochure_item_gateway_command import ShoppingListAddBrochureItemGatewayCommand
from feratel_client.models.shopping_list_add_package_item_gateway_command import ShoppingListAddPackageItemGatewayCommand
from feratel_client.models.shopping_list_add_tour_item_gateway_command import ShoppingListAddTourItemGatewayCommand
from typing import Optional, Set
from typing_extensions import Self

class ShoppingListBulkAddItemsToShoppingListGatewayCommand(BaseModel):
    """
    ShoppingListBulkAddItemsToShoppingListGatewayCommand
    """ # noqa: E501
    add_service_items: Optional[List[ShoppingListAddAdditionalServiceItemGatewayCommand]] = Field(default=None, alias="addServiceItems")
    accommodation_items: Optional[List[ShoppingListAddAccommodationItemGatewayCommand]] = Field(default=None, alias="accommodationItems")
    brochure_items: Optional[List[ShoppingListAddBrochureItemGatewayCommand]] = Field(default=None, alias="brochureItems")
    package_items: Optional[List[ShoppingListAddPackageItemGatewayCommand]] = Field(default=None, alias="packageItems")
    tour_items: Optional[List[ShoppingListAddTourItemGatewayCommand]] = Field(default=None, alias="tourItems")
    __properties: ClassVar[List[str]] = ["addServiceItems", "accommodationItems", "brochureItems", "packageItems", "tourItems"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ShoppingListBulkAddItemsToShoppingListGatewayCommand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in add_service_items (list)
        _items = []
        if self.add_service_items:
            for _item_add_service_items in self.add_service_items:
                if _item_add_service_items:
                    _items.append(_item_add_service_items.to_dict())
            _dict['addServiceItems'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in accommodation_items (list)
        _items = []
        if self.accommodation_items:
            for _item_accommodation_items in self.accommodation_items:
                if _item_accommodation_items:
                    _items.append(_item_accommodation_items.to_dict())
            _dict['accommodationItems'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in brochure_items (list)
        _items = []
        if self.brochure_items:
            for _item_brochure_items in self.brochure_items:
                if _item_brochure_items:
                    _items.append(_item_brochure_items.to_dict())
            _dict['brochureItems'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in package_items (list)
        _items = []
        if self.package_items:
            for _item_package_items in self.package_items:
                if _item_package_items:
                    _items.append(_item_package_items.to_dict())
            _dict['packageItems'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tour_items (list)
        _items = []
        if self.tour_items:
            for _item_tour_items in self.tour_items:
                if _item_tour_items:
                    _items.append(_item_tour_items.to_dict())
            _dict['tourItems'] = _items
        # set to None if add_service_items (nullable) is None
        # and model_fields_set contains the field
        if self.add_service_items is None and "add_service_items" in self.model_fields_set:
            _dict['addServiceItems'] = None

        # set to None if accommodation_items (nullable) is None
        # and model_fields_set contains the field
        if self.accommodation_items is None and "accommodation_items" in self.model_fields_set:
            _dict['accommodationItems'] = None

        # set to None if brochure_items (nullable) is None
        # and model_fields_set contains the field
        if self.brochure_items is None and "brochure_items" in self.model_fields_set:
            _dict['brochureItems'] = None

        # set to None if package_items (nullable) is None
        # and model_fields_set contains the field
        if self.package_items is None and "package_items" in self.model_fields_set:
            _dict['packageItems'] = None

        # set to None if tour_items (nullable) is None
        # and model_fields_set contains the field
        if self.tour_items is None and "tour_items" in self.model_fields_set:
            _dict['tourItems'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ShoppingListBulkAddItemsToShoppingListGatewayCommand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addServiceItems": [ShoppingListAddAdditionalServiceItemGatewayCommand.from_dict(_item) for _item in obj["addServiceItems"]] if obj.get("addServiceItems") is not None else None,
            "accommodationItems": [ShoppingListAddAccommodationItemGatewayCommand.from_dict(_item) for _item in obj["accommodationItems"]] if obj.get("accommodationItems") is not None else None,
            "brochureItems": [ShoppingListAddBrochureItemGatewayCommand.from_dict(_item) for _item in obj["brochureItems"]] if obj.get("brochureItems") is not None else None,
            "packageItems": [ShoppingListAddPackageItemGatewayCommand.from_dict(_item) for _item in obj["packageItems"]] if obj.get("packageItems") is not None else None,
            "tourItems": [ShoppingListAddTourItemGatewayCommand.from_dict(_item) for _item in obj["tourItems"]] if obj.get("tourItems") is not None else None
        })
        return _obj


