# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SkiDataDeliveryModeType(int, Enum):
    """
    SkiDataDeliveryModeType
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_1 = 1
    NUMBER_2 = 2
    NUMBER_4 = 4

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SkiDataDeliveryModeType from a JSON string"""
        return cls(json.loads(json_str))


