# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from feratel_client.models.axess_ticket_item import AxessTicketItem
from feratel_client.models.external_person_information_data import ExternalPersonInformationData
from feratel_client.models.feratel_guest_card_item import FeratelGuestCardItem
from feratel_client.models.ski_data_ticket_item import SkiDataTicketItem
from feratel_client.models.update_ski_data_package_data import UpdateSkiDataPackageData
from feratel_client.models.voucher_data import VoucherData
from feratel_client.models.waldhart_selection import WaldhartSelection
from typing import Optional, Set
from typing_extensions import Self

class UpdateAddServiceExternalData(BaseModel):
    """
    UpdateAddServiceExternalData
    """ # noqa: E501
    ski_data: Optional[List[SkiDataTicketItem]] = Field(default=None, alias="skiData")
    ski_data_package: Optional[UpdateSkiDataPackageData] = Field(default=None, alias="skiDataPackage")
    feratel_guest_card: Optional[List[FeratelGuestCardItem]] = Field(default=None, alias="feratelGuestCard")
    rentmaxx_person_data: Optional[ExternalPersonInformationData] = Field(default=None, alias="rentmaxxPersonData")
    waldhart_selection: Optional[WaldhartSelection] = Field(default=None, alias="waldhartSelection")
    voucher: Optional[VoucherData] = None
    axess: Optional[List[AxessTicketItem]] = None
    __properties: ClassVar[List[str]] = ["skiData", "skiDataPackage", "feratelGuestCard", "rentmaxxPersonData", "waldhartSelection", "voucher", "axess"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateAddServiceExternalData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ski_data (list)
        _items = []
        if self.ski_data:
            for _item_ski_data in self.ski_data:
                if _item_ski_data:
                    _items.append(_item_ski_data.to_dict())
            _dict['skiData'] = _items
        # override the default output from pydantic by calling `to_dict()` of ski_data_package
        if self.ski_data_package:
            _dict['skiDataPackage'] = self.ski_data_package.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in feratel_guest_card (list)
        _items = []
        if self.feratel_guest_card:
            for _item_feratel_guest_card in self.feratel_guest_card:
                if _item_feratel_guest_card:
                    _items.append(_item_feratel_guest_card.to_dict())
            _dict['feratelGuestCard'] = _items
        # override the default output from pydantic by calling `to_dict()` of rentmaxx_person_data
        if self.rentmaxx_person_data:
            _dict['rentmaxxPersonData'] = self.rentmaxx_person_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of waldhart_selection
        if self.waldhart_selection:
            _dict['waldhartSelection'] = self.waldhart_selection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of voucher
        if self.voucher:
            _dict['voucher'] = self.voucher.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in axess (list)
        _items = []
        if self.axess:
            for _item_axess in self.axess:
                if _item_axess:
                    _items.append(_item_axess.to_dict())
            _dict['axess'] = _items
        # set to None if ski_data (nullable) is None
        # and model_fields_set contains the field
        if self.ski_data is None and "ski_data" in self.model_fields_set:
            _dict['skiData'] = None

        # set to None if feratel_guest_card (nullable) is None
        # and model_fields_set contains the field
        if self.feratel_guest_card is None and "feratel_guest_card" in self.model_fields_set:
            _dict['feratelGuestCard'] = None

        # set to None if axess (nullable) is None
        # and model_fields_set contains the field
        if self.axess is None and "axess" in self.model_fields_set:
            _dict['axess'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateAddServiceExternalData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "skiData": [SkiDataTicketItem.from_dict(_item) for _item in obj["skiData"]] if obj.get("skiData") is not None else None,
            "skiDataPackage": UpdateSkiDataPackageData.from_dict(obj["skiDataPackage"]) if obj.get("skiDataPackage") is not None else None,
            "feratelGuestCard": [FeratelGuestCardItem.from_dict(_item) for _item in obj["feratelGuestCard"]] if obj.get("feratelGuestCard") is not None else None,
            "rentmaxxPersonData": ExternalPersonInformationData.from_dict(obj["rentmaxxPersonData"]) if obj.get("rentmaxxPersonData") is not None else None,
            "waldhartSelection": WaldhartSelection.from_dict(obj["waldhartSelection"]) if obj.get("waldhartSelection") is not None else None,
            "voucher": VoucherData.from_dict(obj["voucher"]) if obj.get("voucher") is not None else None,
            "axess": [AxessTicketItem.from_dict(_item) for _item in obj["axess"]] if obj.get("axess") is not None else None
        })
        return _obj


