# coding: utf-8

"""
    Deskline.DS.API

    Description

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from feratel_client.models.update_add_service_external_data import UpdateAddServiceExternalData
from feratel_client.models.update_checkout_question_gateway_command import UpdateCheckoutQuestionGatewayCommand
from typing import Optional, Set
from typing_extensions import Self

class UpdateAdditionalServiceItemGatewayCommand(BaseModel):
    """
    UpdateAdditionalServiceItemGatewayCommand
    """ # noqa: E501
    units: Optional[StrictInt] = None
    external_system_data: Optional[UpdateAddServiceExternalData] = Field(default=None, alias="externalSystemData")
    checkout_questions: Optional[List[UpdateCheckoutQuestionGatewayCommand]] = Field(default=None, alias="checkoutQuestions")
    children_ages: Optional[List[StrictInt]] = Field(default=None, alias="childrenAges")
    __properties: ClassVar[List[str]] = ["units", "externalSystemData", "checkoutQuestions", "childrenAges"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateAdditionalServiceItemGatewayCommand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of external_system_data
        if self.external_system_data:
            _dict['externalSystemData'] = self.external_system_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in checkout_questions (list)
        _items = []
        if self.checkout_questions:
            for _item_checkout_questions in self.checkout_questions:
                if _item_checkout_questions:
                    _items.append(_item_checkout_questions.to_dict())
            _dict['checkoutQuestions'] = _items
        # set to None if checkout_questions (nullable) is None
        # and model_fields_set contains the field
        if self.checkout_questions is None and "checkout_questions" in self.model_fields_set:
            _dict['checkoutQuestions'] = None

        # set to None if children_ages (nullable) is None
        # and model_fields_set contains the field
        if self.children_ages is None and "children_ages" in self.model_fields_set:
            _dict['childrenAges'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateAdditionalServiceItemGatewayCommand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "units": obj.get("units"),
            "externalSystemData": UpdateAddServiceExternalData.from_dict(obj["externalSystemData"]) if obj.get("externalSystemData") is not None else None,
            "checkoutQuestions": [UpdateCheckoutQuestionGatewayCommand.from_dict(_item) for _item in obj["checkoutQuestions"]] if obj.get("checkoutQuestions") is not None else None,
            "childrenAges": obj.get("childrenAges")
        })
        return _obj


